-- =============================================================================
-- Copyright(c) : 
-- Application  : Custom Application
-- -----------------------------------------------------------------------------
-- Program name                 		Creation Date    Original Ver    Created by
-- XX_CUST_REPORT_SUBMITTER_PARAM       28-DEC-2016      1.0          Saugata.
-- -----------------------------------------------------------------------------
-- Usage: Synonym creation script
--
-- -----------------------------------------------------------------------------
-- Description: This is a synonym creation script. This synonym will be use for development
--              of form "Auto Submit Docs". This synonym will keep the line/detail 
--			 	information.
-- CR#			: CHG0039163
-- Parameter    : None
-- Return value : None
-- -----------------------------------------------------------------------------
-- Modification History:
-- Modified Date     Version      Done by       Change Description
-- 
-- =============================================================================
CREATE OR REPLACE SYNONYM XX_CUST_REPORT_SUBMITTER_PARAM FOR XXOBJT.XX_CUST_REPORT_SUBMITTER_PARAM
/ 