insert into XXCOA_INTERCOMPANY_EXCEPTION1 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, DIVISION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (19, 542, 1501, '41', 'Stratasys Direct Inc', '201', '503', 'Solid Concepts do Brasil Ltda (Brazil)', 1);
insert into XXCOA_INTERCOMPANY_EXCEPTION1 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, DIVISION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (19, 542, 1503, '41', 'Stratasys Direct Inc', '202', '207', 'Solid Concepts Shanghai', 1);
insert into XXCOA_INTERCOMPANY_EXCEPTION1 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, DIVISION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (19, 542, 1505, '41', 'Stratasys Direct Inc', '203', '209', 'AMICO', 1);
insert into XXCOA_INTERCOMPANY_EXCEPTION1 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, DIVISION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (27, 590, 1507, '41', 'Stratasys Direct Inc', '201', '503', 'Solid Concepts do Brasil Ltda (Brazil)', 1);
insert into XXCOA_INTERCOMPANY_EXCEPTION1 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, DIVISION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (27, 590, 1509, '41', 'Stratasys Direct Inc', '202', '207', 'Solid Concepts Shanghai', 1);
insert into XXCOA_INTERCOMPANY_EXCEPTION1 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, DIVISION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (27, 590, 1511, '41', 'Stratasys Direct Inc', '203', '209', 'AMICO', 1);
insert into XXCOA_INTERCOMPANY_EXCEPTION1 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, DIVISION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (28, 633, 1513, '41', 'Stratasys Direct Inc', '201', '503', 'Solid Concepts do Brasil Ltda (Brazil)', 1);
insert into XXCOA_INTERCOMPANY_EXCEPTION1 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, DIVISION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (28, 633, 1515, '41', 'Stratasys Direct Inc', '202', '207', 'Solid Concepts Shanghai', 1);
insert into XXCOA_INTERCOMPANY_EXCEPTION1 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, DIVISION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (28, 633, 1517, '41', 'Stratasys Direct Inc', '203', '209', 'AMICO', 1);
insert into XXCOA_INTERCOMPANY_EXCEPTION1 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, DIVISION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (29, 676, 1519, '41', 'Stratasys Direct Inc', '201', '503', 'Solid Concepts do Brasil Ltda (Brazil)', 1);
insert into XXCOA_INTERCOMPANY_EXCEPTION1 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, DIVISION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (29, 676, 1521, '41', 'Stratasys Direct Inc', '202', '207', 'Solid Concepts Shanghai', 1);
insert into XXCOA_INTERCOMPANY_EXCEPTION1 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, DIVISION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (29, 676, 1523, '41', 'Stratasys Direct Inc', '203', '209', 'AMICO', 1);
commit;
/
