insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (20, 'GL', 'SALES');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (21, 'GL', 'COGS');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (22, 'GL', 'EXPENSE');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (23, 'GL', 'BALANCE SHEET ACCOUNT');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (24, 'GL', 'OTHER INCOME EXPENSE');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (25, 'GL', 'TAX RELATED ACCOUNTS');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (27, 'PO', 'ALL');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (28, 'GL', 'ALL');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (29, 'ITEM', 'ALL');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (1, 'ITEM', 'SALES');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (2, 'ITEM', 'COGS');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (3, 'ITEM', 'EXPENSE');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (4, 'ITEM', 'BALANCE SHEET ACCOUNT');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (5, 'ITEM', 'OTHER INCOME EXPENSE');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (6, 'ITEM', 'TAX RELATED ACCOUNTS');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (19, 'ALL', 'ALL');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (26, 'DEFAULT', 'DEFAULT');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (7, 'PO', 'SALES');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (8, 'PO', 'COGS');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (9, 'PO', 'EXPENSE');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (10, 'PO', 'BALANCE SHEET ACCOUNT');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (11, 'PO', 'OTHER INCOME EXPENSE');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (12, 'PO', 'TAX_RELATED_ACCOUNTS');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (13, 'ALL', 'SALES');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (14, 'ALL', 'COGS');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (15, 'ALL', 'EXPENSE');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (16, 'ALL', 'BALANCE SHEET ACCOUNT');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (17, 'ALL', 'OTHER INCOME EXPENSE');
insert into XXCOA_TRANSFORM_KEY (TRANSFORM_ID, ENTITY_TYPE, ACCOUNT_TYPE)
values (18, 'ALL', 'TAX_RELATED_ACCOUNTS');
commit;
/
