insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 670, '41', 'Stratasys Direct Inc', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 671, '41', 'Stratasys Direct Inc', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 672, '41', 'Stratasys Direct Inc', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 500, '49', 'Nadigo Ltd', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 501, '90', 'NA.CO90 - WorkShop', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 502, '48', 'MakerBot general partner DE', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 503, '96', 'Budget Stratasys Inc', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 504, '97', 'Budget Interfacial Solutions', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 505, '99', 'Elimination', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 506, '00', 'None', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 507, '81', 'Desktop Metal', '904', 'Desktop Metal', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 508, '80', 'LPW', '903', 'LPW', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 509, '82', 'Massivit', '902', 'Massivit', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 510, '46', 'Fifth Element Materials LLC', '901', 'Fifth Element Materials LLC', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 511, '53', 'SSYS Mexico', '502', 'Stratasys Mexico', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 512, '43', 'Stratasys Latam', '501', 'Stratasys Latam', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 513, '42', 'Harvest Technologies', '406', 'Harvest Technologies', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 514, '33', 'RedEye', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 515, '31', 'MakerBot Industries', '404', 'MakerBot Industries', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 516, '34', 'Solidscape', '403', 'Solidscape', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 517, '29', 'Seurat Holdings Inc', '402', 'Seurat Holdings Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 518, '23', 'Objet US', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 519, '26', 'Stratasys Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 520, '37', 'Interfacial Solutions', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 521, '44', 'GrabCAD, Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 522, '51', 'Stratasys France Sarl', '306', 'Stratasys France Sarl', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 523, '39', 'Stratasys Switzerland', '305', 'Stratasys Switzerland', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 524, '38', 'Objet UK', '304', 'Objet UK', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 525, '47', 'Econolyst', '304', 'Objet UK', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 526, '35', 'Technimold', '303', 'Technimold', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 527, '27', 'REA Real Estate GmbH', '302', 'REA Real Estate GmbH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 528, '22', 'Objet DE', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 529, '30', 'Old SSYS GMBH', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 530, '40', 'MakerBot Europe KG', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 531, '50', 'RTC Rapid Technologies GmbH', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 532, '52', 'Solid Concepts 3D Printing (Shanghai) Ltd', '207', 'Solid Concepts 3D Printing (Shanghai) Ltd.', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 533, '45', 'Stratasys India', '206', 'Stratasys India (Stratasys India Private Limited)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 534, '36', 'Stratasys Korea', '205', 'Stratasys Korea (Stratasys Korea Ltd)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 535, '32', 'Stratasys Singapore Pte. Ltd', '204', 'Stratasys Singapore (Stratasys Singapore Pte. Ltd)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 536, '25', 'Objet Japan', '203', 'Stratasys Japan  (Stratasys Japan Co., Ltd', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 537, '24', 'Objet CN', '202', 'Stratasys China (Stratasys Shanghai Limited)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 538, '21', 'Objet HK', '201', 'Stratasys AP  (Stratasys AP Limited)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 539, '28', 'Stratasys International Ltd', '102', 'Stratasys International Ltd', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 540, '10', 'Objet IL', '101', 'Stratasys LTD', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (19, 542, '41', 'Stratasys Direct Inc', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (3, 543, 'ALL', 'ALL', null, null, null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 544, '49', 'Nadigo Ltd', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 545, '90', 'NA.CO90 - WorkShop', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 546, '48', 'MakerBot general partner DE', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 547, '96', 'Budget Stratasys Inc', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 548, '97', 'Budget Interfacial Solutions', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 549, '99', 'Elimination', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 550, '00', 'None', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 551, '81', 'Desktop Metal', '904', 'Desktop Metal', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 552, '80', 'LPW', '903', 'LPW', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 553, '82', 'Massivit', '902', 'Massivit', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 554, '46', 'Fifth Element Materials LLC', '901', 'Fifth Element Materials LLC', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 555, '53', 'SSYS Mexico', '502', 'Stratasys Mexico', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 556, '43', 'Stratasys Latam', '501', 'Stratasys Latam', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 557, '42', 'Harvest Technologies', '406', 'Harvest Technologies', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 558, '33', 'RedEye', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 559, '31', 'MakerBot Industries', '404', 'MakerBot Industries', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 560, '34', 'Solidscape', '403', 'Solidscape', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 561, '29', 'Seurat Holdings Inc', '402', 'Seurat Holdings Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 562, '23', 'Objet US', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 563, '26', 'Stratasys Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 564, '37', 'Interfacial Solutions', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 565, '44', 'GrabCAD, Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 566, '51', 'Stratasys France Sarl', '306', 'Stratasys France Sarl', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 567, '39', 'Stratasys Switzerland', '305', 'Stratasys Switzerland', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 568, '38', 'Objet UK', '304', 'Objet UK', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 569, '47', 'Econolyst', '304', 'Objet UK', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 570, '35', 'Technimold', '303', 'Technimold', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 571, '27', 'REA Real Estate GmbH', '302', 'REA Real Estate GmbH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 572, '22', 'Objet DE', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 573, '30', 'Old SSYS GMBH', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 574, '40', 'MakerBot Europe KG', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 575, '50', 'RTC Rapid Technologies GmbH', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 576, '52', 'Solid Concepts 3D Printing (Shanghai) Ltd', '207', 'Solid Concepts 3D Printing (Shanghai) Ltd.', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 577, '45', 'Stratasys India', '206', 'Stratasys India (Stratasys India Private Limited)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 578, '36', 'Stratasys Korea', '205', 'Stratasys Korea (Stratasys Korea Ltd)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 579, '32', 'Stratasys Singapore Pte. Ltd', '204', 'Stratasys Singapore (Stratasys Singapore Pte. Ltd)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 580, '25', 'Objet Japan', '203', 'Stratasys Japan  (Stratasys Japan Co., Ltd', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 581, '24', 'Objet CN', '202', 'Stratasys China (Stratasys Shanghai Limited)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 582, '21', 'Objet HK', '201', 'Stratasys AP  (Stratasys AP Limited)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 583, '28', 'Stratasys International Ltd', '102', 'Stratasys International Ltd', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (27, 584, '10', 'Objet IL', '101', 'Stratasys LTD', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 586, '49', 'Nadigo Ltd', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 587, '90', 'NA.CO90 - WorkShop', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 588, '48', 'MakerBot general partner DE', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 589, '96', 'Budget Stratasys Inc', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 590, '97', 'Budget Interfacial Solutions', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 591, '99', 'Elimination', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 592, '00', 'None', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 593, '81', 'Desktop Metal', '904', 'Desktop Metal', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 594, '80', 'LPW', '903', 'LPW', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 595, '82', 'Massivit', '902', 'Massivit', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 596, '46', 'Fifth Element Materials LLC', '901', 'Fifth Element Materials LLC', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 597, '53', 'SSYS Mexico', '502', 'Stratasys Mexico', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 598, '43', 'Stratasys Latam', '501', 'Stratasys Latam', null);
commit;
prompt 100 records committed...
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 599, '42', 'Harvest Technologies', '406', 'Harvest Technologies', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 600, '33', 'RedEye', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 601, '31', 'MakerBot Industries', '404', 'MakerBot Industries', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 602, '34', 'Solidscape', '403', 'Solidscape', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 603, '29', 'Seurat Holdings Inc', '402', 'Seurat Holdings Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 604, '23', 'Objet US', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 605, '26', 'Stratasys Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 606, '37', 'Interfacial Solutions', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 607, '44', 'GrabCAD, Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 608, '51', 'Stratasys France Sarl', '306', 'Stratasys France Sarl', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 609, '39', 'Stratasys Switzerland', '305', 'Stratasys Switzerland', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 610, '38', 'Objet UK', '304', 'Objet UK', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 611, '47', 'Econolyst', '304', 'Objet UK', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 612, '35', 'Technimold', '303', 'Technimold', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 613, '27', 'REA Real Estate GmbH', '302', 'REA Real Estate GmbH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 614, '22', 'Objet DE', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 615, '30', 'Old SSYS GMBH', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 616, '40', 'MakerBot Europe KG', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 617, '50', 'RTC Rapid Technologies GmbH', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 618, '52', 'Solid Concepts 3D Printing (Shanghai) Ltd', '207', 'Solid Concepts 3D Printing (Shanghai) Ltd.', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 619, '45', 'Stratasys India', '206', 'Stratasys India (Stratasys India Private Limited)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 620, '36', 'Stratasys Korea', '205', 'Stratasys Korea (Stratasys Korea Ltd)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 621, '32', 'Stratasys Singapore Pte. Ltd', '204', 'Stratasys Singapore (Stratasys Singapore Pte. Ltd)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 622, '25', 'Objet Japan', '203', 'Stratasys Japan  (Stratasys Japan Co., Ltd', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 623, '24', 'Objet CN', '202', 'Stratasys China (Stratasys Shanghai Limited)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 624, '21', 'Objet HK', '201', 'Stratasys AP  (Stratasys AP Limited)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 625, '28', 'Stratasys International Ltd', '102', 'Stratasys International Ltd', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (28, 626, '10', 'Objet IL', '101', 'Stratasys LTD', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 628, '49', 'Nadigo Ltd', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 629, '90', 'NA.CO90 - WorkShop', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 630, '48', 'MakerBot general partner DE', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 631, '96', 'Budget Stratasys Inc', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 632, '97', 'Budget Interfacial Solutions', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 633, '99', 'Elimination', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 634, '00', 'None', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 635, '81', 'Desktop Metal', '904', 'Desktop Metal', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 636, '80', 'LPW', '903', 'LPW', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 637, '82', 'Massivit', '902', 'Massivit', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 638, '46', 'Fifth Element Materials LLC', '901', 'Fifth Element Materials LLC', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 639, '53', 'SSYS Mexico', '502', 'Stratasys Mexico', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 640, '43', 'Stratasys Latam', '501', 'Stratasys Latam', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 641, '42', 'Harvest Technologies', '406', 'Harvest Technologies', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 642, '33', 'RedEye', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 643, '31', 'MakerBot Industries', '404', 'MakerBot Industries', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 644, '34', 'Solidscape', '403', 'Solidscape', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 645, '29', 'Seurat Holdings Inc', '402', 'Seurat Holdings Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 646, '23', 'Objet US', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 647, '26', 'Stratasys Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 648, '37', 'Interfacial Solutions', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 649, '44', 'GrabCAD, Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 650, '51', 'Stratasys France Sarl', '306', 'Stratasys France Sarl', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 651, '39', 'Stratasys Switzerland', '305', 'Stratasys Switzerland', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 652, '38', 'Objet UK', '304', 'Objet UK', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 653, '47', 'Econolyst', '304', 'Objet UK', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 654, '35', 'Technimold', '303', 'Technimold', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 655, '27', 'REA Real Estate GmbH', '302', 'REA Real Estate GmbH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 656, '22', 'Objet DE', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 657, '30', 'Old SSYS GMBH', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 658, '40', 'MakerBot Europe KG', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 659, '50', 'RTC Rapid Technologies GmbH', '301', 'Stratasys GMBH', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 660, '52', 'Solid Concepts 3D Printing (Shanghai) Ltd', '207', 'Solid Concepts 3D Printing (Shanghai) Ltd.', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 661, '45', 'Stratasys India', '206', 'Stratasys India (Stratasys India Private Limited)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 662, '36', 'Stratasys Korea', '205', 'Stratasys Korea (Stratasys Korea Ltd)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 663, '32', 'Stratasys Singapore Pte. Ltd', '204', 'Stratasys Singapore (Stratasys Singapore Pte. Ltd)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 664, '25', 'Objet Japan', '203', 'Stratasys Japan  (Stratasys Japan Co., Ltd', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 665, '24', 'Objet CN', '202', 'Stratasys China (Stratasys Shanghai Limited)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 666, '21', 'Objet HK', '201', 'Stratasys AP  (Stratasys AP Limited)', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 667, '28', 'Stratasys International Ltd', '102', 'Stratasys International Ltd', null);
insert into XXCOA_COMPANY (TRANSFORM_ID, COMPANY_ID, LEGACY_COMPANY, LEGACY_COMPANY_DESCRIPTION, S3_COMPANY, S3_COMPANY_DESCRIPTION, ERROR_MESSAGE)
values (29, 668, '10', 'Objet IL', '101', 'Stratasys LTD', null);
commit;
/
