insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (3, 671, 1500, 'ALL', 'ALL', 'GIM', '4000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (3, 671, 1501, 'ALL', 'ALL', 'M01', '4000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (3, 671, 1502, 'ALL', 'ALL', 'T01', '4000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (3, 671, 1503, 'ALL', 'ALL', 'T02', '4000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (3, 671, 1504, 'ALL', 'ALL', 'T03', '4000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (3, 671, 1505, 'ALL', 'ALL', 'S02', '4000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (4, 672, 1506, 'ALL', 'ALL', 'GIM', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (4, 672, 1507, 'ALL', 'ALL', 'M01', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (4, 672, 1508, 'ALL', 'ALL', 'T01', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (4, 672, 1509, 'ALL', 'ALL', 'T02', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (4, 672, 1510, 'ALL', 'ALL', 'T03', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (4, 672, 1511, 'ALL', 'ALL', 'S02', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (5, 673, 1512, 'ALL', 'ALL', 'GIM', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (5, 673, 1513, 'ALL', 'ALL', 'M01', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (5, 673, 1514, 'ALL', 'ALL', 'T01', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (5, 673, 1515, 'ALL', 'ALL', 'T02', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (5, 673, 1516, 'ALL', 'ALL', 'T03', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (5, 673, 1517, 'ALL', 'ALL', 'S02', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (6, 674, 1518, 'ALL', 'ALL', 'GIM', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (6, 674, 1519, 'ALL', 'ALL', 'M01', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (6, 674, 1520, 'ALL', 'ALL', 'T01', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (6, 674, 1521, 'ALL', 'ALL', 'T02', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (6, 674, 1522, 'ALL', 'ALL', 'T03', '0000', null, 1);
insert into XXCOA_DEPARTMENT_EXCEPTION1 (TRANSFORM_ID, DEPARTMENT_ID, EXCEPTION_ID, LEGACY_DEPARTMENT, LEGACY_DEPARTMENT_DESCRIPTION, INVENTORY_ORG, S3_DEPARTMENT, S3_DEPARTMENT_DESCRIPTION, RANK)
values (6, 674, 1523, 'ALL', 'ALL', 'S02', '0000', null, 1);
commit;
/
