insert into XXCOA_INTERCOMPANY_EXCEPTION2 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, INVENTORY_ORG, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (5, 546, 2500, 'ALL', 'ALL', 'GIM', '000', null, 2);
insert into XXCOA_INTERCOMPANY_EXCEPTION2 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, INVENTORY_ORG, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (5, 546, 2501, 'ALL', 'ALL', 'M01', '000', null, 2);
insert into XXCOA_INTERCOMPANY_EXCEPTION2 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, INVENTORY_ORG, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (5, 546, 2502, 'ALL', 'ALL', 'T01', '000', null, 2);
insert into XXCOA_INTERCOMPANY_EXCEPTION2 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, INVENTORY_ORG, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (5, 546, 2503, 'ALL', 'ALL', 'T02', '000', null, 2);
insert into XXCOA_INTERCOMPANY_EXCEPTION2 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, INVENTORY_ORG, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (5, 546, 2504, 'ALL', 'ALL', 'T03', '000', null, 2);
insert into XXCOA_INTERCOMPANY_EXCEPTION2 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, INVENTORY_ORG, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (5, 546, 2505, 'ALL', 'ALL', 'S02', '000', null, 2);
insert into XXCOA_INTERCOMPANY_EXCEPTION2 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, INVENTORY_ORG, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (6, 547, 2506, 'ALL', 'ALL', 'GIM', '000', null, 2);
insert into XXCOA_INTERCOMPANY_EXCEPTION2 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, INVENTORY_ORG, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (6, 547, 2507, 'ALL', 'ALL', 'M01', '000', null, 2);
insert into XXCOA_INTERCOMPANY_EXCEPTION2 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, INVENTORY_ORG, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (6, 547, 2508, 'ALL', 'ALL', 'T01', '000', null, 2);
insert into XXCOA_INTERCOMPANY_EXCEPTION2 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, INVENTORY_ORG, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (6, 547, 2509, 'ALL', 'ALL', 'T02', '000', null, 2);
insert into XXCOA_INTERCOMPANY_EXCEPTION2 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, INVENTORY_ORG, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (6, 547, 2510, 'ALL', 'ALL', 'T03', '000', null, 2);
insert into XXCOA_INTERCOMPANY_EXCEPTION2 (TRANSFORM_ID, INTERCOMPANY_ID, EXCEPTION_ID, LEGACY_INTERCOMPANY, LEGACY_INTERCOMP_DESCRIPTION, INVENTORY_ORG, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, RANK)
values (6, 547, 2511, 'ALL', 'ALL', 'S02', '000', null, 2);
commit;
/