insert into XXCOA_COMPANY_EXCEPTION2 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, INVENTORY_ORG, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (3, 543, 5005, 'ALL', 'ALL', 'T03', '401', null, 2);
insert into XXCOA_COMPANY_EXCEPTION2 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, INVENTORY_ORG, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (3, 543, 5000, 'ALL', 'ALL', 'GIM', '101', null, 2);
insert into XXCOA_COMPANY_EXCEPTION2 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, INVENTORY_ORG, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (3, 543, 5001, 'ALL', 'ALL', 'M01', '401', null, 2);
insert into XXCOA_COMPANY_EXCEPTION2 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, INVENTORY_ORG, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (3, 543, 5002, 'ALL', 'ALL', 'T01', '401', null, 2);
insert into XXCOA_COMPANY_EXCEPTION2 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, INVENTORY_ORG, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (3, 543, 5003, 'ALL', 'ALL', 'T02', '401', null, 2);
insert into XXCOA_COMPANY_EXCEPTION2 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, INVENTORY_ORG, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (3, 543, 5004, 'ALL', 'ALL', 'S02', '401', null, 2);
commit;
/
