insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (1, 1782, 1500, 'ALL', 'ALL', 'GIM', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (1, 1782, 1501, 'ALL', 'ALL', 'M01', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (1, 1782, 1502, 'ALL', 'ALL', 'T01', '501', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (1, 1782, 1503, 'ALL', 'ALL', 'T02', '501', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (1, 1782, 1504, 'ALL', 'ALL', 'T03', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (1, 1782, 1505, 'ALL', 'ALL', 'S02', '501', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (2, 1783, 1506, 'ALL', 'ALL', 'GIM', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (2, 1783, 1507, 'ALL', 'ALL', 'M01', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (2, 1783, 1508, 'ALL', 'ALL', 'T01', '501', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (2, 1783, 1509, 'ALL', 'ALL', 'T02', '501', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (2, 1783, 1510, 'ALL', 'ALL', 'T03', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (2, 1783, 1511, 'ALL', 'ALL', 'S02', '501', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (3, 1784, 1512, 'ALL', 'ALL', 'GIM', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (3, 1784, 1513, 'ALL', 'ALL', 'M01', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (3, 1784, 1514, 'ALL', 'ALL', 'T01', '501', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (3, 1784, 1515, 'ALL', 'ALL', 'T02', '501', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (3, 1784, 1516, 'ALL', 'ALL', 'T03', '501', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (3, 1784, 1517, 'ALL', 'ALL', 'S02', '501', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (4, 1785, 1518, 'ALL', 'ALL', 'GIM', '000', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (4, 1785, 1519, 'ALL', 'ALL', 'M01', '000', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (4, 1785, 1520, 'ALL', 'ALL', 'T01', '000', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (4, 1785, 1521, 'ALL', 'ALL', 'T02', '000', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (4, 1785, 1522, 'ALL', 'ALL', 'T03', '000', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (4, 1785, 1523, 'ALL', 'ALL', 'S02', '000', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (5, 1786, 1524, 'ALL', 'ALL', 'GIM', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (5, 1786, 1525, 'ALL', 'ALL', 'M01', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (5, 1786, 1526, 'ALL', 'ALL', 'T01', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (5, 1786, 1527, 'ALL', 'ALL', 'T02', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (5, 1786, 1528, 'ALL', 'ALL', 'T03', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (5, 1786, 1529, 'ALL', 'ALL', 'S02', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (6, 1787, 1530, 'ALL', 'ALL', 'GIM', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (6, 1787, 1531, 'ALL', 'ALL', 'M01', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (6, 1787, 1532, 'ALL', 'ALL', 'T01', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (6, 1787, 1533, 'ALL', 'ALL', 'T02', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (6, 1787, 1534, 'ALL', 'ALL', 'T03', '890', null, 1);
insert into XXCOA_BUSINESS_UNIT_EXCEPTION1 (TRANSFORM_ID, BU_ID, EXCEPTION_ID, LEGACY_BU, LEGACY_BU_DESCRIPTION, INVENTORY_ORG, S3_BU, S3_BU_DESCRIPTION, RANK)
values (6, 1787, 1535, 'ALL', 'ALL', 'S02', '890', null, 1);
commit;
/
