insert into XXCOA_COMPANY_EXCEPTION1 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, DIVISION, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (19, 542, 1501, '41', 'Stratasys Direct Inc', '201', '503', 'Solid Concepts do Brasil Ltda (Brazil)', 1);
insert into XXCOA_COMPANY_EXCEPTION1 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, DIVISION, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (19, 542, 1503, '41', 'Stratasys Direct Inc', '202', '207', 'Solid Concepts Shanghai', 1);
insert into XXCOA_COMPANY_EXCEPTION1 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, DIVISION, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (19, 542, 1505, '41', 'Stratasys Direct Inc', '203', '209', 'AMICO', 1);
insert into XXCOA_COMPANY_EXCEPTION1 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, DIVISION, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (27, 670, 1579, '41', 'Stratasys Direct Inc', '201', '503', 'Solid Concepts do Brasil Ltda (Brazil)', 1);
insert into XXCOA_COMPANY_EXCEPTION1 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, DIVISION, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (27, 670, 1581, '41', 'Stratasys Direct Inc', '202', '207', 'Solid Concepts Shanghai', 1);
insert into XXCOA_COMPANY_EXCEPTION1 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, DIVISION, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (27, 670, 1583, '41', 'Stratasys Direct Inc', '203', '209', 'AMICO', 1);
insert into XXCOA_COMPANY_EXCEPTION1 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, DIVISION, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (28, 671, 1585, '41', 'Stratasys Direct Inc', '201', '503', 'Solid Concepts do Brasil Ltda (Brazil)', 1);
insert into XXCOA_COMPANY_EXCEPTION1 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, DIVISION, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (28, 671, 1587, '41', 'Stratasys Direct Inc', '202', '207', 'Solid Concepts Shanghai', 1);
insert into XXCOA_COMPANY_EXCEPTION1 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, DIVISION, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (28, 671, 1589, '41', 'Stratasys Direct Inc', '203', '209', 'AMICO', 1);
insert into XXCOA_COMPANY_EXCEPTION1 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, DIVISION, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (29, 672, 1591, '41', 'Stratasys Direct Inc', '201', '503', 'Solid Concepts do Brasil Ltda (Brazil)', 1);
insert into XXCOA_COMPANY_EXCEPTION1 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, DIVISION, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (29, 672, 1593, '41', 'Stratasys Direct Inc', '202', '207', 'Solid Concepts Shanghai', 1);
insert into XXCOA_COMPANY_EXCEPTION1 (TRANSFORM_ID, COMPANY_ID, EXCEPTION_ID, LEGACY_COMPANY, LEGACY_COMP_DESCRIPTION, DIVISION, S3_COMPANY, S3_COMP_DESCRIPTION, RANK)
values (29, 672, 1595, '41', 'Stratasys Direct Inc', '203', '209', 'AMICO', 1);
commit;
/
