insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (3, 323174, 1524, 'ALL', 'ALL', 'GIM', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (3, 323174, 1525, 'ALL', 'ALL', 'M01', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (3, 323174, 1526, 'ALL', 'ALL', 'T01', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (3, 323174, 1527, 'ALL', 'ALL', 'T02', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (3, 323174, 1528, 'ALL', 'ALL', 'T03', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (3, 323174, 1529, 'ALL', 'ALL', 'S02', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (4, 323175, 1530, 'ALL', 'ALL', 'GIM', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (4, 323175, 1531, 'ALL', 'ALL', 'M01', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (4, 323175, 1532, 'ALL', 'ALL', 'T01', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (4, 323175, 1533, 'ALL', 'ALL', 'T02', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (4, 323175, 1534, 'ALL', 'ALL', 'T03', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (4, 323175, 1535, 'ALL', 'ALL', 'S02', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (5, 323176, 1536, 'ALL', 'ALL', 'GIM', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (5, 323176, 1537, 'ALL', 'ALL', 'M01', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (5, 323176, 1538, 'ALL', 'ALL', 'T01', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (5, 323176, 1539, 'ALL', 'ALL', 'T02', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (5, 323176, 1540, 'ALL', 'ALL', 'T03', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (5, 323176, 1541, 'ALL', 'ALL', 'S02', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (6, 323177, 1542, 'ALL', 'ALL', 'GIM', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (6, 323177, 1543, 'ALL', 'ALL', 'M01', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (6, 323177, 1544, 'ALL', 'ALL', 'T01', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (6, 323177, 1545, 'ALL', 'ALL', 'T02', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (6, 323177, 1546, 'ALL', 'ALL', 'T03', '0000', null, 1);
insert into XXCOA_PRODUCTLINE_EXCEPTION1 (TRANSFORM_ID, PL_ID, EXCEPTION_ID, LEGACY_ITEM_NUMBER, LEGACY_DESCRIPTION, INVENTORY_ORG, S3_PL, S3_PL_DESCRIPTION, RANK)
values (6, 323177, 1547, 'ALL', 'ALL', 'S02', '0000', null, 1);
commit;
/