insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 670, '25', 'Objet Japan', '203', 'Stratasys Japan  (Stratasys Japan Co., Ltd', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 671, '24', 'Objet CN', '202', 'Stratasys China (Stratasys Shanghai Limited)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 548, '49', 'Nadigo Ltd', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 549, '90', 'NA.CO90 - WorkShop', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 550, '48', 'MakerBot general partner DE', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 551, '96', 'Budget Stratasys Inc', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 552, '97', 'Budget Interfacial Solutions', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 553, '99', 'Elimination', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 554, '00', 'None', '000', 'Valid for Intercompany mapping S3 Segment7 only', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 555, '81', 'Desktop Metal', '904', 'Desktop Metal', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 556, '80', 'LPW', '903', 'LPW', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 557, '82', 'Massivit', '902', 'Massivit', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 558, '46', 'Fifth Element Materials LLC', '901', 'Fifth Element Materials LLC', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 559, '53', 'SSYS Mexico', '502', 'Stratasys Mexico', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 560, '43', 'Stratasys Latam', '501', 'Stratasys Latam', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 561, '42', 'Harvest Technologies', '406', 'Harvest Technologies', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 562, '33', 'RedEye', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 563, '31', 'MakerBot Industries', '404', 'MakerBot Industries', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 564, '34', 'Solidscape', '403', 'Solidscape', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 565, '29', 'Seurat Holdings Inc', '402', 'Seurat Holdings Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 566, '23', 'Objet US', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 567, '26', 'Stratasys Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 568, '37', 'Interfacial Solutions', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 569, '44', 'GrabCAD, Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 570, '51', 'Stratasys France Sarl', '306', 'Stratasys France Sarl', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 571, '39', 'Stratasys Switzerland', '305', 'Stratasys Switzerland', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 572, '38', 'Objet UK', '304', 'Objet UK', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 573, '47', 'Econolyst', '304', 'Objet UK', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 574, '35', 'Technimold', '303', 'Technimold', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 575, '27', 'REA Real Estate GmbH', '302', 'REA Real Estate GmbH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 576, '22', 'Objet DE', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 577, '30', 'Old SSYS GMBH', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 578, '40', 'MakerBot Europe KG', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 579, '50', 'RTC Rapid Technologies GmbH', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 580, '52', 'Solid Concepts 3D Printing (Shanghai) Ltd', '207', 'Solid Concepts 3D Printing (Shanghai) Ltd.', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 581, '45', 'Stratasys India', '206', 'Stratasys India (Stratasys India Private Limited)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 582, '36', 'Stratasys Korea', '205', 'Stratasys Korea (Stratasys Korea Ltd)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 583, '32', 'Stratasys Singapore Pte. Ltd', '204', 'Stratasys Singapore (Stratasys Singapore Pte. Ltd)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 584, '25', 'Objet Japan', '203', 'Stratasys Japan  (Stratasys Japan Co., Ltd', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 585, '24', 'Objet CN', '202', 'Stratasys China (Stratasys Shanghai Limited)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 586, '21', 'Objet HK', '201', 'Stratasys AP  (Stratasys AP Limited)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 587, '28', 'Stratasys International Ltd', '102', 'Stratasys International Ltd', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 588, '10', 'Objet IL', '101', 'Stratasys LTD', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (27, 590, '41', 'Stratasys Direct Inc', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 591, '49', 'Nadigo Ltd', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 592, '90', 'NA.CO90 - WorkShop', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 593, '48', 'MakerBot general partner DE', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 594, '96', 'Budget Stratasys Inc', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 595, '97', 'Budget Interfacial Solutions', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 596, '99', 'Elimination', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 597, '00', 'None', '000', 'Valid for Intercompany mapping S3 Segment7 only', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 598, '81', 'Desktop Metal', '904', 'Desktop Metal', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 599, '80', 'LPW', '903', 'LPW', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 600, '82', 'Massivit', '902', 'Massivit', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 601, '46', 'Fifth Element Materials LLC', '901', 'Fifth Element Materials LLC', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 602, '53', 'SSYS Mexico', '502', 'Stratasys Mexico', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 603, '43', 'Stratasys Latam', '501', 'Stratasys Latam', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 604, '42', 'Harvest Technologies', '406', 'Harvest Technologies', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 605, '33', 'RedEye', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 606, '31', 'MakerBot Industries', '404', 'MakerBot Industries', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 607, '34', 'Solidscape', '403', 'Solidscape', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 608, '29', 'Seurat Holdings Inc', '402', 'Seurat Holdings Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 609, '23', 'Objet US', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 610, '26', 'Stratasys Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 611, '37', 'Interfacial Solutions', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 612, '44', 'GrabCAD, Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 613, '51', 'Stratasys France Sarl', '306', 'Stratasys France Sarl', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 614, '39', 'Stratasys Switzerland', '305', 'Stratasys Switzerland', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 615, '38', 'Objet UK', '304', 'Objet UK', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 616, '47', 'Econolyst', '304', 'Objet UK', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 617, '35', 'Technimold', '303', 'Technimold', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 618, '27', 'REA Real Estate GmbH', '302', 'REA Real Estate GmbH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 619, '22', 'Objet DE', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 620, '30', 'Old SSYS GMBH', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 621, '40', 'MakerBot Europe KG', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 622, '50', 'RTC Rapid Technologies GmbH', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 623, '52', 'Solid Concepts 3D Printing (Shanghai) Ltd', '207', 'Solid Concepts 3D Printing (Shanghai) Ltd.', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 624, '45', 'Stratasys India', '206', 'Stratasys India (Stratasys India Private Limited)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 625, '36', 'Stratasys Korea', '205', 'Stratasys Korea (Stratasys Korea Ltd)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 626, '32', 'Stratasys Singapore Pte. Ltd', '204', 'Stratasys Singapore (Stratasys Singapore Pte. Ltd)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 627, '25', 'Objet Japan', '203', 'Stratasys Japan  (Stratasys Japan Co., Ltd', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 628, '24', 'Objet CN', '202', 'Stratasys China (Stratasys Shanghai Limited)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 629, '21', 'Objet HK', '201', 'Stratasys AP  (Stratasys AP Limited)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 630, '28', 'Stratasys International Ltd', '102', 'Stratasys International Ltd', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 631, '10', 'Objet IL', '101', 'Stratasys LTD', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (28, 633, '41', 'Stratasys Direct Inc', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 634, '49', 'Nadigo Ltd', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 635, '90', 'NA.CO90 - WorkShop', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 636, '48', 'MakerBot general partner DE', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 637, '96', 'Budget Stratasys Inc', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 638, '97', 'Budget Interfacial Solutions', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 639, '99', 'Elimination', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 640, '00', 'None', '000', 'Valid for Intercompany mapping S3 Segment7 only', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 641, '81', 'Desktop Metal', '904', 'Desktop Metal', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 642, '80', 'LPW', '903', 'LPW', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 643, '82', 'Massivit', '902', 'Massivit', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 644, '46', 'Fifth Element Materials LLC', '901', 'Fifth Element Materials LLC', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 645, '53', 'SSYS Mexico', '502', 'Stratasys Mexico', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 646, '43', 'Stratasys Latam', '501', 'Stratasys Latam', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 647, '42', 'Harvest Technologies', '406', 'Harvest Technologies', null);
commit;
prompt 100 records committed...
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 648, '33', 'RedEye', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 649, '31', 'MakerBot Industries', '404', 'MakerBot Industries', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 650, '34', 'Solidscape', '403', 'Solidscape', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 651, '29', 'Seurat Holdings Inc', '402', 'Seurat Holdings Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 652, '23', 'Objet US', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 653, '26', 'Stratasys Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 654, '37', 'Interfacial Solutions', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 655, '44', 'GrabCAD, Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 656, '51', 'Stratasys France Sarl', '306', 'Stratasys France Sarl', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 657, '39', 'Stratasys Switzerland', '305', 'Stratasys Switzerland', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 658, '38', 'Objet UK', '304', 'Objet UK', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 659, '47', 'Econolyst', '304', 'Objet UK', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 660, '35', 'Technimold', '303', 'Technimold', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 661, '27', 'REA Real Estate GmbH', '302', 'REA Real Estate GmbH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 662, '22', 'Objet DE', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 663, '30', 'Old SSYS GMBH', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 664, '40', 'MakerBot Europe KG', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 665, '50', 'RTC Rapid Technologies GmbH', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 666, '52', 'Solid Concepts 3D Printing (Shanghai) Ltd', '207', 'Solid Concepts 3D Printing (Shanghai) Ltd.', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 667, '45', 'Stratasys India', '206', 'Stratasys India (Stratasys India Private Limited)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 668, '36', 'Stratasys Korea', '205', 'Stratasys Korea (Stratasys Korea Ltd)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 669, '32', 'Stratasys Singapore Pte. Ltd', '204', 'Stratasys Singapore (Stratasys Singapore Pte. Ltd)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 672, '21', 'Objet HK', '201', 'Stratasys AP  (Stratasys AP Limited)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 673, '28', 'Stratasys International Ltd', '102', 'Stratasys International Ltd', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 674, '10', 'Objet IL', '101', 'Stratasys LTD', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (29, 676, '41', 'Stratasys Direct Inc', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (6, 547, 'ALL', 'ALL', null, null, null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 500, '49', 'Nadigo Ltd', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 501, '90', 'NA.CO90 - WorkShop', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 502, '48', 'MakerBot general partner DE', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 503, '96', 'Budget Stratasys Inc', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 504, '97', 'Budget Interfacial Solutions', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 505, '99', 'Elimination', null, null, 'Invalid Company Code' || chr(13) || '');
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 506, '00', 'None', '000', 'Valid for Intercompany mapping S3 Segment7 only', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 507, '81', 'Desktop Metal', '904', 'Desktop Metal', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 508, '80', 'LPW', '903', 'LPW', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 509, '82', 'Massivit', '902', 'Massivit', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 510, '46', 'Fifth Element Materials LLC', '901', 'Fifth Element Materials LLC', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 511, '53', 'SSYS Mexico', '502', 'Stratasys Mexico', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 512, '43', 'Stratasys Latam', '501', 'Stratasys Latam', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 513, '42', 'Harvest Technologies', '406', 'Harvest Technologies', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 514, '33', 'RedEye', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 515, '31', 'MakerBot Industries', '404', 'MakerBot Industries', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 516, '34', 'Solidscape', '403', 'Solidscape', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 517, '29', 'Seurat Holdings Inc', '402', 'Seurat Holdings Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 518, '23', 'Objet US', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 519, '26', 'Stratasys Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 520, '37', 'Interfacial Solutions', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 521, '44', 'GrabCAD, Inc', '401', 'Stratasys Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 522, '51', 'Stratasys France Sarl', '306', 'Stratasys France Sarl', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 523, '39', 'Stratasys Switzerland', '305', 'Stratasys Switzerland', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 524, '38', 'Objet UK', '304', 'Objet UK', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 525, '47', 'Econolyst', '304', 'Objet UK', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 526, '35', 'Technimold', '303', 'Technimold', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 527, '27', 'REA Real Estate GmbH', '302', 'REA Real Estate GmbH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 528, '22', 'Objet DE', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 529, '30', 'Old SSYS GMBH', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 530, '40', 'MakerBot Europe KG', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 531, '50', 'RTC Rapid Technologies GmbH', '301', 'Stratasys GMBH', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 532, '52', 'Solid Concepts 3D Printing (Shanghai) Ltd', '207', 'Solid Concepts 3D Printing (Shanghai) Ltd.', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 533, '45', 'Stratasys India', '206', 'Stratasys India (Stratasys India Private Limited)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 534, '36', 'Stratasys Korea', '205', 'Stratasys Korea (Stratasys Korea Ltd)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 535, '32', 'Stratasys Singapore Pte. Ltd', '204', 'Stratasys Singapore (Stratasys Singapore Pte. Ltd)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 536, '25', 'Objet Japan', '203', 'Stratasys Japan  (Stratasys Japan Co., Ltd', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 537, '24', 'Objet CN', '202', 'Stratasys China (Stratasys Shanghai Limited)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 538, '21', 'Objet HK', '201', 'Stratasys AP  (Stratasys AP Limited)', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 539, '28', 'Stratasys International Ltd', '102', 'Stratasys International Ltd', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 540, '10', 'Objet IL', '101', 'Stratasys LTD', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (19, 542, '41', 'Stratasys Direct Inc', '405', 'Stratasys Direct Inc', null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (15, 543, 'ALL', 'ALL', '000', null, null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (17, 544, 'ALL', 'ALL', '000', null, null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (18, 545, 'ALL', 'ALL', '000', null, null);
insert into XXCOA_INTERCOMPANY (TRANSFORM_ID, INTERCOMPANY_ID, LEGACY_INTERCOMPANY_VALUE, LEGACY_INTERCOMP_DESCRIPTION, S3_INTERCOMPANY, S3_INTERCOMP_DESCRIPTION, ERROR_MESSAGE)
values (5, 546, 'ALL', 'ALL', null, null, null);
commit;
/
