insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (4, 665, 1518, 'ALL', 'ALL', 'GIM', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (4, 665, 1519, 'ALL', 'ALL', 'M01', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (4, 665, 1520, 'ALL', 'ALL', 'T01', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (4, 665, 1521, 'ALL', 'ALL', 'T02', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (4, 665, 1522, 'ALL', 'ALL', 'T03', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (4, 665, 1523, 'ALL', 'ALL', 'S02', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (5, 666, 1524, 'ALL', 'ALL', 'GIM', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (5, 666, 1525, 'ALL', 'ALL', 'M01', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (5, 666, 1526, 'ALL', 'ALL', 'T01', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (5, 666, 1527, 'ALL', 'ALL', 'T02', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (5, 666, 1528, 'ALL', 'ALL', 'T03', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (5, 666, 1529, 'ALL', 'ALL', 'S02', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (6, 667, 1530, 'ALL', 'ALL', 'GIM', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (6, 667, 1531, 'ALL', 'ALL', 'M01', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (6, 667, 1532, 'ALL', 'ALL', 'T01', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (6, 667, 1533, 'ALL', 'ALL', 'T02', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (6, 667, 1534, 'ALL', 'ALL', 'T03', '000', null, 1);
insert into XXCOA_LOCATION_EXCEPTION1 (TRANSFORM_ID, LOCATION_ID, EXCEPTION_ID, LEGACY_LOCATION, LEGACY_LOCATION_DESCRIPTION, INVENTORY_ORG, S3_LOCATION, S3_LOCATION_DESCRIPTION, RANK)
values (6, 667, 1535, 'ALL', 'ALL', 'S02', '000', null, 1);
commit;
/
