insert into XXCOA_ACCOUNT_EXCEPTION1 (TRANSFORM_ID, ACCOUNT_ID, EXCEPTION_ID, LEGACY_ACCOUNT, LEGACY_ACCOUNT_DESCRIPTION, INVENTORY_ORG, S3_ACCOUNT, S3_ACCOUNT_DESCRIPTION, RANK)
values (3, 1955, 1500, 'ALL', 'ALL', 'GIM', '699998', null, 1);
insert into XXCOA_ACCOUNT_EXCEPTION1 (TRANSFORM_ID, ACCOUNT_ID, EXCEPTION_ID, LEGACY_ACCOUNT, LEGACY_ACCOUNT_DESCRIPTION, INVENTORY_ORG, S3_ACCOUNT, S3_ACCOUNT_DESCRIPTION, RANK)
values (3, 1955, 1501, 'ALL', 'ALL', 'M01', '699998', null, 1);
insert into XXCOA_ACCOUNT_EXCEPTION1 (TRANSFORM_ID, ACCOUNT_ID, EXCEPTION_ID, LEGACY_ACCOUNT, LEGACY_ACCOUNT_DESCRIPTION, INVENTORY_ORG, S3_ACCOUNT, S3_ACCOUNT_DESCRIPTION, RANK)
values (3, 1955, 1502, 'ALL', 'ALL', 'T01', '699998', null, 1);
insert into XXCOA_ACCOUNT_EXCEPTION1 (TRANSFORM_ID, ACCOUNT_ID, EXCEPTION_ID, LEGACY_ACCOUNT, LEGACY_ACCOUNT_DESCRIPTION, INVENTORY_ORG, S3_ACCOUNT, S3_ACCOUNT_DESCRIPTION, RANK)
values (3, 1955, 1503, 'ALL', 'ALL', 'T02', '699998', null, 1);
insert into XXCOA_ACCOUNT_EXCEPTION1 (TRANSFORM_ID, ACCOUNT_ID, EXCEPTION_ID, LEGACY_ACCOUNT, LEGACY_ACCOUNT_DESCRIPTION, INVENTORY_ORG, S3_ACCOUNT, S3_ACCOUNT_DESCRIPTION, RANK)
values (3, 1955, 1504, 'ALL', 'ALL', 'T03', '699998', null, 1);
insert into XXCOA_ACCOUNT_EXCEPTION1 (TRANSFORM_ID, ACCOUNT_ID, EXCEPTION_ID, LEGACY_ACCOUNT, LEGACY_ACCOUNT_DESCRIPTION, INVENTORY_ORG, S3_ACCOUNT, S3_ACCOUNT_DESCRIPTION, RANK)
values (3, 1955, 1505, 'ALL', 'ALL', 'S02', '699998', null, 1);
commit;
/
