insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 532, 2282, '26', '600000', '699999', null, null, null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 533, 2282, '26', '251290', '251290', null, null, '000', '000', '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 500, 2282, '26', '400000', '499999', '00', '00', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 501, 2282, '26', '400000', '499999', '01', '99', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 502, 2282, '26', '500000', '599999', '01', '99', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 503, 2282, '26', '501000', '501059', '00', '00', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 504, 2282, '26', '501060', '580010', '00', '00', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 505, 2282, '26', '580030', '580030', '00', '00', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 506, 2282, '26', '580200', '599510', '00', '00', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 507, 2282, '26', '700000', '999999', '00', '99', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 508, 2282, '26', '100000', '251109', '00', '99', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 509, 2282, '26', '251110', '251110', null, null, null, null, '9999', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 510, 2282, '26', '251111', '251289', '00', '99', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 511, 2282, '26', '251290', '251290', null, null, '890', '890', '5103', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 512, 2282, '26', '251290', '251290', null, null, '999', '999', '5203', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 513, 2282, '26', '251291', '251299', '00', '99', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 514, 2282, '26', '251300', '251300', null, null, '000', '099', '9999', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 515, 2282, '26', '251300', '251300', null, null, '100', '199', '5104', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 516, 2282, '26', '251300', '251300', null, null, '200', '299', '5204', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 517, 2282, '26', '251300', '251300', null, null, '500', '599', '5104', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 518, 2282, '26', '251300', '251300', null, null, '700', '799', '5204', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 519, 2282, '26', '251300', '251300', null, null, '800', '899', '5104', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 520, 2282, '26', '251300', '251300', null, null, '900', '999', '5204', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 521, 2282, '26', '251301', '399999', '00', '99', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 522, 2282, '37', '100000', '251109', '00', '99', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 523, 2282, '37', '251110', '251110', null, null, null, null, '9999', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 524, 2282, '37', '251111', '399999', '00', '99', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 525, 2282, '37', '400000', '999999', '00', '99', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 526, 2282, '44', '100000', '251109', '00', '99', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 527, 2282, '44', '251110', '251110', null, null, null, null, '9999', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 528, 2282, '44', '251111', '399999', '00', '99', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 529, 2282, '44', '400000', '999999', '00', '99', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 530, 2408, '29', '100000', '399999', '00', '99', null, null, '0000', null);
insert into XXCOA_GL_PRODUCT_LINE (TRANSFORM_ID, PL_ID, SOB_ID, LEGACY_COMPANY, LEGACY_ACCOUNT_FROM, LEGACY_ACCOUNT_TO, LEGACY_INTER_COMPANY_FROM, LEGACY_INTER_COMPANY_TO, PRODUCT_LINE_FROM, PRODUCT_LINE_TO, S3_PRODUCT_LINE, ERROR_MESSAGE)
values (28, 531, 2408, '29', '400000', '999999', '00', '99', null, null, '0000', null);
commit;
/
