insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '163', 'Added 9/22 Used for Open Transactions only; no longer valid in S3', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '265', 'Added 9/22 Used for Open Transactions only; no longer valid in S3', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '340', 'Added 9/22 Used for Open Transactions only; no longer valid in S3', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '425', 'Added 9/22 Used for Open Transactions only; no longer valid in S3', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '591', 'Added 9/22 Used for Open Transactions only; no longer valid in S3', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '593', 'Added 9/22 Used for Open Transactions only; no longer valid in S3', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '594', 'Added 9/22 Used for Open Transactions only; no longer valid in S3', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '710', 'Added 9/22 Used for Open Transactions only; no longer valid in S3', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '33', 'NA', 'NA', 'Invalid');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '100', 'Manufacturing', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '110', 'Manufacturing Chemistry', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '115', 'Filament Extrusion', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '116', 'Recycling', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '120', 'Manufacturing Systems', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '121', 'Direct Labor - Dimension / P-Class', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '122', 'Direct Labor - uPrint', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '123', 'Direct Labor - Other', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '124', 'Direct Labor - Mojo', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '125', 'Direct Labor - Fortus / 900mc', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '126', 'Direct Labor - Fortus / T-class', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '141', 'Direct Labor - Filament Extrusion', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '142', 'Direct Labor - Filament Compounding', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '161', 'Direct Labor - Refurb', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '162', 'Direct Labor - RedEye Machine Operations', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '209', 'MB Operations', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '210', 'Operations ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '211', 'Operations Management - NA ***Driven by BU/Company***', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '215', 'Facilities- General ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '216', 'Facilities- Operations ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '217', 'Facilities- North America Sales ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '218', 'Facilities- R&D', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '219', 'Facilities- Innovation', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '220', 'Facilities- SMACS', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '221', 'Facilities- Edenvale ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '222', 'Facilities - Wallace ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '230', 'Quality Operations', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '235', 'Strategic Sourcing', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '236', 'Indirect Sourcing', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '250', 'New FDM Plant ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '260', 'Refurb', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '266', 'RedEye Service Bureau Support', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '280', 'Global Ops - Leadership', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '281', 'Global Ops - Management System', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '282', 'Global Ops - Manufacturing & Quality', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '283', 'Global Ops - Fulfillment & Distribution', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '284', 'Global Ops - Sourcing', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '285', 'Global Ops - Product Compliance', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '290', '<<Disabled>>', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '291', 'Desktop', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '292', 'Office', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '293', 'Professional', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '294', 'Polyjet Resin', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '295', 'Refurbish', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '296', 'Spare Parts', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '298', 'Supply Chain Management', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '309', 'MB Service', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '310', 'Service ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '320', 'Post Sales ***Collapsing into Legacy 310***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '330', 'Professional Services', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '350', 'Econolyst limited ***Driven by BU/Company***', '240');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '360', 'CS North America ***Driven by BU/Company***', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '370', 'EMEA CS ***Driven by BU/Company***', '201');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '380', 'LATAM CS ***Driven by BU/Company***', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '400', 'R&D', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '410', 'R&D', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '415', 'GC R&D', '550');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '420', 'R&D Engineering', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '430', 'R&D Materials Development', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '431', 'SLS', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '432', 'SLA', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '435', 'R&D Technology Development', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '436', 'Technology Development - Shadow', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '437', 'Skunkworks 1', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '438', 'Skunkworks 2', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '450', 'New Production Introduction', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '455', 'Test & Automation', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '460', 'Products and Global Technology', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '480', 'Innovation 1', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '481', 'Innovation 2', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '490', 'Supported R&D', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '500', 'Sales & Marketing', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '509', 'MB Marketing ***Driven by BU/Company***', '401');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '510', 'Marketing ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '511', 'Marcom', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '512', 'PR', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '513', 'Marketing Operations', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '514', 'Branding', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '519', 'MB Sales ***Driven by BU/Company***', '401');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '520', 'Product Marketing', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '530', 'Sales Enablement', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '535', 'BI', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '536', 'Sales Operations ***Driven by BU/Company***', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '540', 'Marketing North America ***Driven by BU/Company***', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '545', 'Materials Business Unit ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '546', 'Materials Region ***Driven by BU/Company***', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '550', 'CBO', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '551', 'Field Operations ***Driven by BU/Company***', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '552', 'Channel Sales', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '553', 'Commercial Sales', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '554', 'Channel Development ***Collapsing into Legacy 552***', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '555', 'Sale Chanel/Application ***Collapsing into Legacy 552***', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '556', 'RedEye Service Bureau Sales Support', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '557', 'Region Vertical Business Unit ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '558', 'Region SAM ***Driven by BU/Company***', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '559', 'Corp SAM ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '560', 'Sales North America ***Driven by BU/Company***', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '561', 'Customer Advocacy', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '565', 'Sales Operations (A/E) North America ***Collapsing into Legacy 575***', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '570', 'EMEA CBO ***Driven by BU/Company***', '201');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '571', 'GC Marketing', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '575', 'Applications', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '580', 'LATAM Marketing ***Driven by BU/Company***', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '585', 'LATAM CBO ***Driven by BU/Company***', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '589', 'VBU- Aero/Auto', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '590', 'Business Development', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '592', 'Harp', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '595', 'Corp Vertical Business Unit', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '596', 'VBU- Medical', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '597', 'VBU- Education', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '598', 'VBU- Dental', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '599', 'VBU- Manufacturing', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '600', 'General Administration', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '601', 'Rehovot New Building ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '609', 'MB G&A ***Driven by BU/Company***', '401');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '610', 'G&A ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '611', 'Intellectual Property', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '612', 'G&A Legal', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '615', 'General Facilities ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '620', 'HR ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '621', 'HR Region ***Driven by BU/Company***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '630', 'IT Effectiveness', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '631', 'IT Applications - Finance/OPS', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '632', 'IT Applications - HMS', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '633', 'IT Infrastructure - Network', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '634', 'IT Infrastructure - Data Center/OPS', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '635', 'S3 Project', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '640', '<<Disabled>>', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '650', 'Corp Quality Management ***Collapsing into Legacy 282***', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '660', 'G&A North America ***Driven by BU/Company***', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '665', 'G&A Corp MN', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '670', 'EMEA G&A ***Driven by BU/Company***', '201');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '680', 'LATAM G&A ***Driven by BU/Company***', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '700', 'Finance Expenses', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '800', 'Tax', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '899', 'FA General (Sub Inventory Only)', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '<<NEW>>', null, 'NA');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '000', 'None', '000');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '001', 'Evo', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '002', 'Rhone', '#N/A');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '010', 'Product Cogs non gaap', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '011', 'Service Cogs non gaap', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '012', 'R&D non gaap', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '013', 'Sales non gaap', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '014', 'Marketing non gaap', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '015', 'G&A non gaap', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('602', 'Japan', 'not applicable', 'not applicable', 'not applicable', '121');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('603', 'Tokyo', 'not applicable', 'not applicable', 'not applicable', '121');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('604', 'Osaka', 'not applicable', 'not applicable', 'not applicable', '121');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('611', 'Australia', 'not applicable', 'not applicable', 'not applicable', '161');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('612', 'China', 'not applicable', 'not applicable', 'not applicable', '111');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('613', 'Hong Kong', 'not applicable', 'not applicable', 'not applicable', '113');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('614', 'India', 'not applicable', 'not applicable', 'not applicable', '140');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('615', 'Indonesia', 'not applicable', 'not applicable', 'not applicable', '151');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('616', 'Korea', 'not applicable', 'not applicable', 'not applicable', '131');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('617', 'Malaysia', 'not applicable', 'not applicable', 'not applicable', '151');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('618', 'New Zealand', 'not applicable', 'not applicable', 'not applicable', '161');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('619', 'Philippines', 'not applicable', 'not applicable', 'not applicable', '151');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('620', 'Singapore', 'not applicable', 'not applicable', 'not applicable', '151');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('621', 'Taiwan', 'not applicable', 'not applicable', 'not applicable', '115');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('622', 'Thailand', 'not applicable', 'not applicable', 'not applicable', '151');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('624', 'Viet Nam', 'not applicable', 'not applicable', 'not applicable', '151');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('628', 'Sri Lanka', 'not applicable', 'not applicable', 'not applicable', '140');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('629', 'Zhongshan', 'not applicable', 'not applicable', 'not applicable', '111');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('202', 'Belarus', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('223', 'Russian Federation', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('253', 'Ukraine', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('247', 'Bulgaria', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('207', 'Czech Republic', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('248', 'Estonia', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('249', 'Hungary', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('216', 'Latvia', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('251', 'Lithuania', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('220', 'Poland', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('252', 'Romania', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('224', 'Slovakia', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('219', 'Norway', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('203', 'Belgium', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('208', 'Denmark', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('209', 'Finland', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('214', 'Ireland', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('238', 'Luxembourg', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('218', 'Netherlands', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('229', 'Sweden', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('233', 'United Kingdom', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('236', 'Liechtenstein', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('230', 'Switzerland', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('201', 'Austria', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('211', 'Germany', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('206', 'Croatia', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('212', 'Kosovo', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('245', 'Serbia', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('246', 'Turkey', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('242', 'Cyprus', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('243', 'Greece', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('215', 'Italy', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('225', 'Slovenia', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('244', 'Jordan', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('623', 'United Arab Emirates', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('205', 'Reunion', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('235', 'Andorra', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('237', 'Monaco', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('210', 'France', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('221', 'Portugal', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('227', 'Spain', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('254', 'Egypt', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('255', 'Kenya', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('256', 'Nigeria', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('257', 'South Africa', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('240', 'Tanzania, United Republic of', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('102', 'Israel', 'not applicable', 'not applicable', 'not applicable', '890');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('303', 'Brazil', 'not applicable', 'not applicable', 'not applicable', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('302', 'Argentina', 'not applicable', 'not applicable', 'not applicable', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('339', 'Bolivia', 'not applicable', 'not applicable', 'not applicable', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('305', 'Chile', 'not applicable', 'not applicable', 'not applicable', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('306', 'Colombia', 'not applicable', 'not applicable', 'not applicable', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('333', 'Costa Rica', 'not applicable', 'not applicable', 'not applicable', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('320', 'Republica Dominicana', 'not applicable', 'not applicable', 'not applicable', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('335', 'Ecuador', 'not applicable', 'not applicable', 'not applicable', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('338', 'Guatemala', 'not applicable', 'not applicable', 'not applicable', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('341', 'Peru', 'not applicable', 'not applicable', 'not applicable', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('336', 'Uruguay', 'not applicable', 'not applicable', 'not applicable', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('342', 'Venezuela, Bolivarian Republic of', 'not applicable', 'not applicable', 'not applicable', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('310', 'Mexico', 'not applicable', 'not applicable', 'not applicable', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('340', 'Puerto Rico', 'not applicable', 'not applicable', 'not applicable', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('337', 'Trinidad and Tobago', 'not applicable', 'not applicable', 'not applicable', '370');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '34', 'not applicable', 'not applicable', '561');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '37', 'not applicable', 'not applicable', '570');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '46', 'not applicable', 'not applicable', '571');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '44', 'not applicable', 'not applicable', '550');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '515', 'GMN Sales', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '316', 'GMN Regional Ops', '501');
insert into XXS3_BU_US_PO_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, LEGACY_DEPARTMENT, DESCRIPTION_OF_DEPARTMENT, S3_BUSINESS_UNIT)
values ('not applicable', 'not applicable', '26', '315', 'GMN Corporate Ops', '890');
commit;
/
