insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('000', 'Default', '000', 'Default');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('102', 'Israel', '102', 'Israel');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('991', 'Kyriat Gat', '103', 'Kyriat Gat');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('992', 'Rehovot', '104', 'Rehovot');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('201', 'Austria', '201', 'Austria');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('202', 'Belarus', '202', 'Belarus');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('203', 'Belgium', '203', 'Belgium');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('204', 'Macedonia', '204', 'Macedonia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('205', 'Reunion', '205', 'Reunion');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('206', 'Croatia', '206', 'Croatia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('207', 'Czech Republic', '207', 'Czech Republic');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('208', 'Denmark', '208', 'Denmark');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('209', 'Finland', '209', 'Finland');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('210', 'France', '210', 'France');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('211', 'Germany', '211', 'Germany');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('212', 'Kosovo', '212', 'Kosovo');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('214', 'Ireland', '214', 'Ireland');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('215', 'Italy', '215', 'Italy');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('216', 'Latvia', '216', 'Latvia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('218', 'Netherlands', '218', 'Netherlands');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('219', 'Norway', '219', 'Norway');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('220', 'Poland', '220', 'Poland');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('221', 'Portugal', '221', 'Portugal');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('223', 'Russian Federation', '223', 'Russian Federation');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('224', 'Slovakia', '224', 'Slovakia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('225', 'Slovenia', '225', 'Slovenia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('226', 'Georgia', '226', 'Georgia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('227', 'Spain', '227', 'Spain');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('229', 'Sweden', '229', 'Sweden');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('230', 'Switzerland', '230', 'Switzerland');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('233', 'United Kingdom', '233', 'United Kingdom');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('235', 'Andorra', '235', 'Andorra');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('236', 'Liechtenstein', '236', 'Liechtenstein');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('237', 'Monaco', '237', 'Monaco');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('238', 'Luxembourg', '238', 'Luxembourg');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('240', 'Tanzania, United Republic of', '240', 'Tanzania, United Republic of');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('307', 'Cyprus', '242', 'Cyprus');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('308', 'Greece', '243', 'Greece');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('319', 'Jordan', '244', 'Jordan');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('318', 'Serbia', '245', 'Serbia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('316', 'Turkey', '246', 'Turkey');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('304', 'Bulgaria', '247', 'Bulgaria');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('323', 'Estonia', '248', 'Estonia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('309', 'Hungary', '249', 'Hungary');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('329', 'Kazakhstan', '250', 'Kazakhstan');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('325', 'Lithuania', '251', 'Lithuania');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('312', 'Romania', '252', 'Romania');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('317', 'Ukraine', '253', 'Ukraine');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('324', 'Egypt', '254', 'Egypt');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('330', 'Kenya', '255', 'Kenya');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('328', 'Nigeria', '256', 'Nigeria');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('313', 'South Africa', '257', 'South Africa');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('302', 'Argentina', '302', 'Argentina');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('303', 'Brazil', '303', 'Brazil');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('305', 'Chile', '305', 'Chile');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('306', 'Colombia', '306', 'Colombia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('310', 'Mexico', '310', 'Mexico');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('311', 'Panama', '311', 'Panama');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('320', 'Republica Dominicana', '320', 'Republica Dominicana');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('333', 'Costa Rica', '333', 'Costa Rica');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('334', 'El Salvador', '334', 'El Salvador');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('104', 'Ecuador', '335', 'Ecuador');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('105', 'Uruguay', '336', 'Uruguay');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('106', 'Trinidad and Tobago', '337', 'Trinidad and Tobago');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('107', 'Guatemala', '338', 'Guatemala');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('108', 'Bolivia', '339', 'Bolivia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('109', 'Puerto Rico', '340', 'Puerto Rico');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('222', 'Peru', '341', 'Peru');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('234', 'Venezuela, Bolivarian Republic of', '342', 'Venezuela, Bolivarian Republic of');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('602', 'Japan', '602', 'Japan');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('na', 'New', '603', 'Tokyo');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('na', 'New', '604', 'Osaka');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('611', 'Australia', '611', 'Australia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('612', 'China', '612', 'China');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('613', 'Hong Kong', '613', 'Hong Kong');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('614', 'India', '614', 'India');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('615', 'Indonesia', '615', 'Indonesia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('616', 'Korea, Republic of', '616', 'Korea, Republic of');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('617', 'Malaysia', '617', 'Malaysia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('618', 'New Zealand', '618', 'New Zealand');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('619', 'Philippines', '619', 'Philippines');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('620', 'Singapore', '620', 'Singapore');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('621', 'Taiwan', '621', 'Taiwan');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('622', 'Thailand', '622', 'Thailand');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('623', 'United Arab Emirates', '623', 'United Arab Emirates');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('624', 'Viet Nam', '624', 'Viet Nam');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('625', 'Shanghai', '625', 'Shanghai');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('626', 'Beijing', '626', 'Beijing');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('627', 'South Asia', '627', 'South Asia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('628', 'Sri Lanka', '628', 'Sri Lanka');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('631', 'Greater China', '631', 'Greater China');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('632', 'Shenzhen', '632', 'Shenzhen');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('na', 'New', '633', 'Zhongshan');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('801', 'Canada', '801', 'Canada');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('802', 'Samoa', '802', 'Samoa');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('803', 'United States', '803', 'United States');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('912', 'GU - GUAM', '804', 'Guam');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('901', 'AL - ALABAMA', '901', 'AL - Alabama');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('902', 'AK - ALASKA', '902', 'AK - Alaska');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('903', 'AZ - ARIZONA', '903', 'AZ - Arizona');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('904', 'AR - ARKANSAS', '904', 'AR - Arkansas');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('905', 'CA - CALIFORNIA', '905', 'CA - California');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('906', 'CO - COLORADO', '906', 'CO - Colorado');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('907', 'CT - CONNECTICUT', '907', 'CT - Connecticut');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('908', 'DE - DELAWARE', '908', 'DE - Delaware');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('909', 'DC - DISTRICT OF COLUMBIA', '909', 'DC - District of Columbia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('910', 'FL - FLORIDA', '910', 'FL - Florida');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('911', 'GA - GEORGIA', '911', 'GA - Georgia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('913', 'HI - HAWAII', '913', 'HI - Hawaii');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('914', 'ID - IDAHO', '914', 'ID - Idaho');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('915', 'IL - ILLINOIS', '915', 'IL - Illinois');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('916', 'IN - INDIANA', '916', 'IN - Indiana');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('917', 'IA - IOWA', '917', 'IA - Iowa');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('918', 'KS - KANSAS', '918', 'KS - Kansas');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('919', 'KY - KENTUCKY', '919', 'KY - Kentucky');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('920', 'LA - LOUISIANA', '920', 'LA - Louisiana');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('921', 'ME - MAINE', '921', 'ME - Maine');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('922', 'MD - MARYLAND', '922', 'MD - Maryland');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('923', 'MA - MASSACHUSETTS', '923', 'MA - Massachusetts');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('924', 'MI - MICHIGAN', '924', 'MI - Michigan');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('925', 'MN - MINNESOTA', '925', 'MN - Minnesota');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('926', 'MS - MISSISSIPPI', '926', 'MS - Mississippi');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('927', 'MO - MISSOURI', '927', 'MO - Missouri');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('928', 'MT - MONTANA', '928', 'MT - Montana');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('929', 'NE - NEBRASKA', '929', 'NE - Nebraska');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('930', 'NV - NEVADA', '930', 'NV - Nevada');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('931', 'NH - NEW HAMPSHIRE', '931', 'NH - New Hampshire');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('932', 'NJ - NEW JERSEY', '932', 'NJ - New Jersey');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('933', 'NM - NEW MEXICO', '933', 'NM - New Mexico');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('934', 'NY - NEW YORK', '934', 'NY - New York');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('935', 'NC - NORTH CAROLINA', '935', 'NC - North Carolina');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('936', 'ND - NORTH DAKOTA', '936', 'ND - North Dakota');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('937', 'OH - OHIO', '937', 'OH - Ohio');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('938', 'OK - OKLAHOMA', '938', 'OK - Oklahoma');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('939', 'OR - OREGON', '939', 'OR - Oregon');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('940', 'PA - PENNSYLVANIA', '940', 'PA - Pennsylvania');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('941', 'RI - RHODE ISLAND', '941', 'RI - Rhode Island');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('942', 'SC - SOUTH CAROLINA', '942', 'SC - South Carolina');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('943', 'SD - SOUTH DAKOTA', '943', 'SD - South Dakota');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('944', 'TN - TENNESSEE', '944', 'TN - Tennessee');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('945', 'TX - TEXAS', '945', 'TX - Texas');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('946', 'UT - UTAH', '946', 'UT - Utah');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('947', 'VT - VERMONT', '947', 'VT - Vermont');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('948', 'VA - VIRGINIA', '948', 'VA - Virginia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('949', 'WA - WASHINGTON', '949', 'WA - Washington');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('950', 'WV - WEST VIRGINIA', '950', 'WV - West Virginia');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('951', 'WI - WISCONSIN', '951', 'WI - Wisconsin');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('952', 'WY - WYOMING', '952', 'WY - Wyoming');
insert into XXS3_LOCATION_TRANSFORM (LEGACY_LOCATION, LOCATION_DESCRIPTION, S3_LOCATION, DESCRIPTION_OF_LOCATION)
values ('997', 'Hong Kong', '613', 'Hong Kong');
commit;
/

