insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('315', 'GMN Corporate Ops', '3020', 'GMN Services Ops');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('316', 'GMN Regional Ops', '3020', 'GMN Services Ops');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('515', 'GMN Sales', '5610', 'GMN Management');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('100', 'Manufacturing', '890', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('110', 'Manufacturing Chemistry', '1300', 'Manufacturing OH - Resin');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('115', 'Filament Extrusion', '1200', 'Manufacturing OH - Filament');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('116', 'Recycling', '1620', 'Recycling');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('120', 'Manufacturing Systems', '1100', 'Manufacturing OH - System');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('121', 'Direct Labor - Dimension / P-Class', '1110', 'Direct Labor - System');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('122', 'Direct Labor - uPrint', '1110', 'Direct Labor - System');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('123', 'Direct Labor - Other', '1110', 'Direct Labor - System');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('124', 'Direct Labor - Mojo', '1110', 'Direct Labor - System');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('125', 'Direct Labor - Fortus / 900mc', '1110', 'Direct Labor - System');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('126', 'Direct Labor - Fortus / T-class', '1110', 'Direct Labor - System');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('141', 'Direct Labor - Filament Extrusion', '1210', 'Direct Labor - Filament');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('142', 'Direct Labor - Filament Compounding', '1210', 'Direct Labor - Filament');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('161', 'Direct Labor - Refurb', '1410', 'Direct Labor - Refurb');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('162', 'Direct Labor - RedEye Machine Operations', '890', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('163', 'Direct Labor - RedEye Finishing Operations', '9999', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('209', 'MB Operations', '890', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('210', 'Operations ***Driven by BU/Company***', '1000', 'Operations Management');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('211', 'Operations Management - NA ***Driven by BU/Company***', '1000', 'Operations Management');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('215', 'Facilities- General ***Driven by BU/Company***', '7800', 'Facilities- General');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('216', 'Facilities- Operations ***Driven by BU/Company***', '7810', 'Facilities- Operations');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('217', 'Facilities- North America Sales ***Driven by BU/Company***', '7820', 'Facilities- Sales Office');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('218', 'Facilities- R&D', '7830', 'Facilities- R&D');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('219', 'Facilities- Innovation', '7840', 'Facilities- Innovation');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('220', 'Facilities- SMACS', '7850', 'Facilities- Infrastructure');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('221', 'Facilities- Edenvale ***Driven by BU/Company***', '7860', 'Facilities- Headquarters');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('222', 'Facilities - Wallace ***Driven by BU/Company***', '7810', 'Facilities- Operations');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('230', 'Quality Operations', '1500', 'Quality Operations - Plant');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('235', 'Strategic Sourcing', '1520', 'Strategic Sourcing');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('236', 'Indirect Sourcing', '1530', 'Indirect Sourcing');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('250', 'New FDM Plant ***Driven by BU/Company***', '7810', 'Facilities- Operations');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('260', 'Refurb', '1400', 'Manufacturing OH - Refurb');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('265', 'RedEye Service Operations', '9999', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('266', 'RedEye Service Bureau Support', '3020', 'GMN Service Operations');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('280', 'Global Ops - Leadership', '1800', 'Global Ops - Product Compliance');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('281', 'Global Ops - Management System', '1810', 'Global Ops - Management System');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('282', 'Global Ops - Manufacturing & Quality', '1820', 'Global Ops - Manufacturing & Quality');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('283', 'Global Ops - Fulfillment & Distribution', '1830', 'Global Ops - Fulfillment & Distribution');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('284', 'Global Ops - Sourcing', '1840', 'Global Ops - Sourcing');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('285', 'Global Ops - Product Compliance', '1850', 'Global Ops - Product Compliance');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('290', '<<Disabled>>', '890', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('291', 'Desktop', '1110', 'Direct Labor - System');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('292', 'Office', '1110', 'Direct Labor - System');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('293', 'Professional', '1110', 'Direct Labor - System');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('294', 'Polyjet Resin', '1310', 'Direct Labor - Resin');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('295', 'Refurbish', '1410', 'Direct Labor - Refurb');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('296', 'Spare Parts', '1410', 'Direct Labor - Refurb');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('298', 'Supply Chain Management', '1540', 'Supply Chain Management');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('309', 'MB Service', '890', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('310', 'Service ***Driven by BU/Company***', '3000', 'Service');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('320', 'Post Sales ***Collapsing into Legacy 310***', '3000', 'Service');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('330', 'Professional Services', '3010', 'Professional Services');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('340', 'VBU - Medical Service', '9999', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('350', 'Econolyst limited ***Driven by BU/Company***', '3000', 'Service');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('360', 'CS North America ***Driven by BU/Company***', '3000', 'Service');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('370', 'EMEA CS ***Driven by BU/Company***', '3000', 'Service');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('380', 'LATAM CS ***Driven by BU/Company***', '3000', 'Service');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('400', 'R&D', '890', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('410', 'R&D', '4000', 'R&D Management');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('415', 'GC R&D', '4000', 'R&D Management');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('420', 'R&D Engineering', '4200', 'Engineering');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('425', '<<Disabled>>', '9999', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('430', 'R&D Materials Development', '4300', 'R&D Materials Development');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('431', 'SLS', '4700', 'SLA');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('432', 'SLA', '4710', 'SLS');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('435', 'R&D Technology Development', '4400', 'R&D Technology Development');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('436', 'Technology Development - Shadow', '4410', 'Technology Development - Shadow');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('437', 'Skunkworks 1', '4600', 'Skunkworks 1');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('438', 'Skunkworks 2', '4610', 'Skunkworks 2');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('450', 'New Production Introduction', '1600', 'New Production Introduction');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('455', 'Test & Automation', '1610', 'Test & Automation');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('460', 'Products and Global Technology', '4100', 'Products and Global Technology');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('480', 'Innovation 1', '4800', 'R&D Innovation 1');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('481', 'Innovation 2', '4810', 'R&D Innovation 2');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('490', 'Supported R&D', '890', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('500', 'Sales & Marketing', '890', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('509', 'MB Marketing ***Driven by BU/Company***', '6000', 'Marketing');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('510', 'Marketing ***Driven by BU/Company***', '6000', 'Marketing');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('511', 'Marcom', '6100', 'MARCOM');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('512', 'PR', '6110', 'PR');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('513', 'Marketing Operations', '6120', 'Marketing Operations');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('514', 'Branding', '9999', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('519', 'MB Sales ***Driven by BU/Company***', '5210', 'Sales Operations');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('520', 'Product Marketing', '6130', 'Product Management');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('530', 'Sales Enablement', '6140', 'Sales Enablement');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('535', 'BI', '5300', 'BI');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('536', 'Sales Operations ***Driven by BU/Company***', '5210', 'Sales Operations');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('540', 'Marketing North America ***Driven by BU/Company***', '6000', 'Marketing');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('545', 'Materials Business Unit ***Driven by BU/Company***', '5100', 'Materials');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('546', 'Materials Region ***Driven by BU/Company***', '5100', 'Materials');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('550', 'CBO', '5000', 'Sales Management');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('551', 'Field Operations ***Driven by BU/Company***', '5210', 'Sales Operations');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('552', 'Channel Sales', '5230', 'Channel');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('553', 'Commercial Sales', '5220', 'Commercial');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('554', 'Channel Development ***Collapsing into Legacy 552***', '5230', 'Channel');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('555', 'Sale Chanel/Application ***Collapsing into Legacy 552***', '5230', 'Channel');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('556', 'RedEye Service Bureau Sales Support', '5610', 'GMN Management');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('557', 'Region Vertical Business Unit ***Driven by BU/Company***', '9999', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('558', 'Region SAM ***Driven by BU/Company***', '5600', 'SAM');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('559', 'Corp SAM ***Driven by BU/Company***', '5600', '^^^Same as above^^^');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('560', 'Sales North America ***Driven by BU/Company***', '5210', 'Sales Operations');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('561', 'Customer Advocacy', '5240', 'Customer Advocacy');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('565', 'Sales Operations (A/E) North America ***Collapsing into Legacy 575***', '5200', 'Benchmark-Applications');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('570', 'EMEA CBO ***Driven by BU/Company***', '5210', 'Sales Operations');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('571', 'GC Marketing', '890', '3-Oct updated to default');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('575', 'Applications', '5200', 'Benchmark-Applications');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('580', 'LATAM Marketing ***Driven by BU/Company***', '6000', 'Marketing');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('585', 'LATAM CBO ***Driven by BU/Company***', '5210', 'Sales Operations');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('589', 'VBU- Aero/Auto', '5550', 'VBU Aero/Auto');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('590', 'Business Development', '6150', 'Business Development');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('591', 'Baccio/Eagle', '9999', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('592', 'Harp', '7990', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('593', 'Fusion', '9999', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('594', 'Polar Bear', '7310', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('595', 'Corp Vertical Business Unit', '5500', 'VBU Management');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('596', 'VBU- Medical', '5510', 'VBU Medical');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('597', 'VBU- Education', '5520', 'VBU Education');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('598', 'VBU- Dental', '5530', 'VBU Dental');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('599', 'VBU- Manufacturing', '5540', 'VBU Manufacturing');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('600', 'General Administration', '890', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('601', 'Rehovot New Building ***Driven by BU/Company***', '7860', 'Facilities- Headquarters');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('609', 'MB G&A ***Driven by BU/Company***', '7000', 'G&A');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('610', 'G&A ***Driven by BU/Company***', '7000', 'G&A');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('611', 'Intellectual Property', '7020', 'IP');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('612', 'G&A Legal', '7030', 'Legal');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('615', 'General Facilities ***Driven by BU/Company***', '7800', 'Facilities- General');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('620', 'HR ***Driven by BU/Company***', '7200', 'HR');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('621', 'HR Region ***Driven by BU/Company***', '7200', 'HR');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('630', 'IT Effectiveness', '7300', 'IT Effectiveness');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('631', 'IT Applications - Finance/OPS', '7310', 'IT Applications- Finance/Operations');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('632', 'IT Applications - HMS', '7320', 'IT Applications- HMS');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('633', 'IT Infrastructure - Network', '7330', 'IT Infrastructure- Network');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('634', 'IT Infrastructure - Data Center/OPS', '7340', 'IT Infrastructure- Data Center/Operations');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('635', 'S3 Project', '7350', 'IT Transformation');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('640', '<<Disabled>>', '890', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('650', 'Corp Quality Management ***Collapsing into Legacy 282***', '1820', 'Global Ops - Manufacturing & Quality');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('660', 'G&A North America ***Driven by BU/Company***', '7000', 'G&A');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('665', 'G&A Corp MN', '7010', 'Corp. Accounting');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('670', 'EMEA G&A ***Driven by BU/Company***', '7000', 'G&A');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('680', 'LATAM G&A ***Driven by BU/Company***', '7000', 'G&A');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('700', 'Finance Expenses', '890', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('710', 'Finance expense', '7310', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('800', 'Tax', '890', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('899', 'FA General (Sub Inventory Only)', '890', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('<<NEW>>', null, '1510', 'Operations Scaling ');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('000', 'None', '0000', 'May be used on all account types except Expense accounts (which begin with a 6). See item master tab for exception rules');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('001', 'Evo', '890', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('002', 'Rhone', '890', null);
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('010', 'Product Cogs non gaap', '1990', 'Products non-GAAP');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('011', 'Service Cogs non gaap', '3990', 'Service non-GAAP');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('012', 'R&D non gaap', '4990', 'R&D non-GAAP');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('013', 'Sales non gaap', '5990', 'Sales non-GAAP');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('014', 'Marketing non gaap', '6990', 'Marketing non-GAAP');
insert into XXS3_DEPARTMENT_TRANSFORM (LEGACY_DEPARTMENT, DEPARTMENT_DESCRIPTION, DEPARTMENT, DESCRIPTION_OF_DEPARTMENT)
values ('015', 'G&A non gaap', '7990', 'G&A non-GAAP');
commit;
/


