insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '951', 'WI - Wisconsin', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '952', 'WY - Wyoming', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', 'not applicable', 'not applicable', '34', '561', 'Solidscape');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', 'not applicable', 'not applicable', '37', '570', 'AMC');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', 'not applicable', 'not applicable', '46', '571', '5EM');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', 'not applicable', 'not applicable', '44', '550', 'Grabcad');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '602', 'Japan', 'not applicable', '121', 'SSYS Japan Direct');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '603', 'Tokyo', 'not applicable', '121', 'SSYS Japan Direct');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '604', 'Osaka', 'not applicable', '121', 'SSYS Japan Direct');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '611', 'Australia', 'not applicable', '161', 'SSYS ANZ');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '612', 'China', 'not applicable', '111', 'SSYS China Direct');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '613', 'Hong Kong', 'not applicable', '113', 'SSYS HK Direct');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '614', 'India', 'not applicable', '140', 'SSYS India');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '615', 'Indonesia', 'not applicable', '151', 'SSYS SEA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '616', 'Korea', 'not applicable', '131', 'SSYS Korea Direct');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '617', 'Malaysia', 'not applicable', '151', 'SSYS SEA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '618', 'New Zealand', 'not applicable', '161', 'SSYS ANZ');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '619', 'Philippines', 'not applicable', '151', 'SSYS SEA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '620', 'Singapore', 'not applicable', '151', 'SSYS SEA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '621', 'Taiwan', 'not applicable', '115', 'SSYS Taiwan');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '622', 'Thailand', 'not applicable', '151', 'SSYS SEA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '624', 'Viet Nam', 'not applicable', '151', 'SSYS SEA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '628', 'Sri Lanka', 'not applicable', '140', 'SSYS India');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('APJ', '629', 'Zhongshan', 'not applicable', '111', 'SSYS China Direct');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '202', 'Belarus', 'not applicable', '231', 'CEE');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '223', 'Russian Federation', 'not applicable', '231', 'CEE');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '253', 'Ukraine', 'not applicable', '231', 'CEE');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '247', 'Bulgaria', 'not applicable', '231', 'CEE');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '207', 'Czech Republic', 'not applicable', '231', 'CEE');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '248', 'Estonia', 'not applicable', '231', 'CEE');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '249', 'Hungary', 'not applicable', '231', 'CEE');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '216', 'Latvia', 'not applicable', '231', 'CEE');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '251', 'Lithuania', 'not applicable', '231', 'CEE');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '220', 'Poland', 'not applicable', '231', 'CEE');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '252', 'Romania', 'not applicable', '231', 'CEE');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '224', 'Slovakia', 'not applicable', '231', 'CEE');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '219', 'Norway', 'not applicable', '211', 'UK+Benelux+Nordics');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '203', 'Belgium', 'not applicable', '211', 'UK+Benelux+Nordics');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '208', 'Denmark', 'not applicable', '211', 'UK+Benelux+Nordics');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '209', 'Finland', 'not applicable', '211', 'UK+Benelux+Nordics');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '214', 'Ireland', 'not applicable', '211', 'UK+Benelux+Nordics');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '238', 'Luxembourg', 'not applicable', '211', 'UK+Benelux+Nordics');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '218', 'Netherlands', 'not applicable', '211', 'UK+Benelux+Nordics');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '229', 'Sweden', 'not applicable', '211', 'UK+Benelux+Nordics');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '233', 'United Kingdom', 'not applicable', '211', 'UK+Benelux+Nordics');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '236', 'Liechtenstein', 'not applicable', '201', 'DACH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '230', 'Switzerland', 'not applicable', '201', 'DACH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '201', 'Austria', 'not applicable', '201', 'DACH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '211', 'Germany', 'not applicable', '201', 'DACH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '206', 'Croatia', 'not applicable', '226', 'Italy+SEE+ME');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '212', 'Kosovo', 'not applicable', '226', 'Italy+SEE+ME');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '245', 'Serbia', 'not applicable', '226', 'Italy+SEE+ME');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '246', 'Turkey', 'not applicable', '226', 'Italy+SEE+ME');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '242', 'Cyprus', 'not applicable', '226', 'Italy+SEE+ME');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '243', 'Greece', 'not applicable', '226', 'Italy+SEE+ME');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '215', 'Italy', 'not applicable', '226', 'Italy+SEE+ME');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '225', 'Slovenia', 'not applicable', '226', 'Italy+SEE+ME');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '244', 'Jordan', 'not applicable', '226', 'Italy+SEE+ME');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '623', 'United Arab Emirates', 'not applicable', '226', 'Italy+SEE+ME');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '205', 'Reunion', 'not applicable', '221', 'France+Iberia+FSA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '235', 'Andorra', 'not applicable', '221', 'France+Iberia+FSA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '237', 'Monaco', 'not applicable', '221', 'France+Iberia+FSA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '210', 'France', 'not applicable', '221', 'France+Iberia+FSA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '221', 'Portugal', 'not applicable', '221', 'France+Iberia+FSA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '227', 'Spain', 'not applicable', '221', 'France+Iberia+FSA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '254', 'Egypt', 'not applicable', '205', 'Israel+ESA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '255', 'Kenya', 'not applicable', '205', 'Israel+ESA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '256', 'Nigeria', 'not applicable', '205', 'Israel+ESA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '257', 'South Africa', 'not applicable', '205', 'Israel+ESA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '240', 'Tanzania, United Republic of', 'not applicable', '205', 'Israel+ESA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('EMEA', '102', 'Israel', 'not applicable', '205', 'Israel+ESA');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('LATAM', '303', 'Brazil', 'not applicable', '372', 'Brazil');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('LATAM', '302', 'Argentina', 'not applicable', '371', 'South Cone');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('LATAM', '339', 'Bolivia', 'not applicable', '371', 'South Cone');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('LATAM', '305', 'Chile', 'not applicable', '371', 'South Cone');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('LATAM', '306', 'Colombia', 'not applicable', '371', 'South Cone');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('LATAM', '333', 'Costa Rica', 'not applicable', '371', 'South Cone');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('LATAM', '320', 'Republica Dominicana', 'not applicable', '371', 'South Cone');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('LATAM', '335', 'Ecuador', 'not applicable', '371', 'South Cone');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('LATAM', '338', 'Guatemala', 'not applicable', '371', 'South Cone');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('LATAM', '341', 'Peru', 'not applicable', '371', 'South Cone');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('LATAM', '336', 'Uruguay', 'not applicable', '371', 'South Cone');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('LATAM', '342', 'Venezuela, Bolivarian Republic of', 'not applicable', '371', 'South Cone');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('LATAM', '310', 'Mexico', 'not applicable', '373', 'Mexico');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('LATAM', '340', 'Puerto Rico', 'not applicable', '373', 'Mexico');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('LATAM', '337', 'Trinidad and Tobago', 'not applicable', '373', 'Mexico');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '801', 'Canada', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '802', 'Samoa', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '803', 'United States', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '804', 'Guam', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '901', 'AL - Alabama', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '902', 'AK - Alaska', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '903', 'AZ - Arizona', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '904', 'AR - Arkansas', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '905', 'CA - California', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '906', 'CO - Colorado', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '907', 'CT - Connecticut', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '908', 'DE - Delaware', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '909', 'DC - District of Columbia', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '910', 'FL - Florida', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '911', 'GA - Georgia', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '913', 'HI - Hawaii', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '914', 'ID - Idaho', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '915', 'IL - Illinois', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '916', 'IN - Indiana', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '917', 'IA - Iowa', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '918', 'KS - Kansas', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '919', 'KY - Kentucky', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '920', 'LA - Louisiana', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '921', 'ME - Maine', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '922', 'MD - Maryland', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '923', 'MA - Massachusetts', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '924', 'MI - Michigan', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '925', 'MN - Minnesota', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '926', 'MS - Mississippi', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '927', 'MO - Missouri', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '928', 'MT - Montana', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '929', 'NE - Nebraska', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '930', 'NV - Nevada', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '931', 'NH - New Hampshire', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '932', 'NJ - New Jersey', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '933', 'NM - New Mexico', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '934', 'NY - New York', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '935', 'NC - North Carolina', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '936', 'ND - North Dakota', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '937', 'OH - Ohio', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '938', 'OK - Oklahoma', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '939', 'OR - Oregon', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '940', 'PA - Pennsylvania', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '941', 'RI - Rhode Island', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '942', 'SC - South Carolina', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '943', 'SD - South Dakota', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '944', 'TN - Tennessee', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '945', 'TX - Texas', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '946', 'UT - Utah', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '947', 'VT - Vermont', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '948', 'VA - Virginia', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '949', 'WA - Washington', 'not applicable', '501', 'SSYS NASH');
insert into XXS3_BU_SC_TRANSFORM (REGION, LEGACY_LOCATION, LOCATION_DESCRIPTION, LEGACY_COMPANY, S3_BUSINESS_UNIT, DESCRIPTION_OR_REGION_NAME)
values ('NA', '950', 'WV - West Virginia', 'not applicable', '501', 'SSYS NASH');
commit;
/

