CREATE OR REPLACE TRIGGER XXINV_TRX_MATERIAL_IN_BI_TRG BEFORE INSERT ON XXOBJT.XXINV_TRX_MATERIAL_IN
FOR EACH ROW

BEGIN
	:NEW.LAST_UPDATE_DATE := SYSDATE;
	:NEW.LAST_UPDATED_BY  := fnd_global.USER_ID;
  :NEW.TRX_ID:=XXINV_TRX_IN_S.NEXTVAL;
END;
/