/*
  Program          :  Create view of AR Payments Schedules
  Filename         :  XXAR_PAYMENTS_SCHEULES_V.SQL

  Purpose          :  Display information about AR Payment Schedules to be use for 
                   :  OBIEE reporting.  This ties to the XXAR_Aging_v but is at a
                   :  more detail level to help with drill-down analysis. 
                    
  Change History   :
  ............................................................
 --  ver  date               name                             desc
 --  1.0  11/04/2014    John Hendrickson           CHG0031451 initial build

  ............................................................
*/
CREATE OR REPLACE VIEW XXBI.xxar_payment_schedules_v (PAYMENT_SCHEDULE_ID, DUE_DATE, CLASS, ITEM_STATUS
, EARNED_DISCOUNT_TAKEN, UNEARNED_DISCOUNT_TAKEN, GENERAL_LEDGER_DATE, ORIGINAL_AMOUNT_DUE, BALANCE_DUE
, ORIGINAL_LINE_AMOUNT, REMAINING_LINE_AMOUNT, ORIGINAL_FREIGHT, REMAINING_FREIGHT, ORIGINAL_TAX, REMAINING_TAX
, AMOUNT_CREDITED, RECEIVABLE_CHARGES_CHARGED, RECEIVABLE_CHARGES_REMAINING
, BALANCE_DUE_IN_FUNCTIONAL_CURR, EARNED_DISCOUNT_TAKEN_FUNC, UNEARNED_DISCOUNT_TAKEN_FUNC, ORIGINAL_AMOUNT_DUE_FUNC 
, ORIGINAL_LINE_AMOUNT_FUNC, REMAINING_LINE_AMOUNT_FUNC, ORIGINAL_FREIGHT_FUNC, REMAINING_FREIGHT_FUNC, ORIGINAL_TAX_FUNC, REMAINING_TAX_FUNC
, AMOUNT_CREDITED_FUNC, RECEIVABLE_CHARGES_FUNC, RECEIVABLE_CHG_REMAINING_FUNC
, CURRENCY_EXCHANGE_RATE, CURRENCY_EXCHANGE_RATE_TYPE, CURRENCY_EXCHANGE_RATE_DATE
, TOTAL_NUMBER_OF_INSTALLMENTS, INSTALLMENT_SEQUENCE_NUMBER, DISPUTE_AMOUNT, DISPUTE_DATE, SCHEDULE_CLOSED_DATE
, ACTUAL_DATE_CLOSED, IN_COLLECTION_FLAG, LAST_CALL_DATE, LAST_FOLLOW_UP_OUTCOME, LAST_FOLLOW_UP_DATE
, LAST_PROMISE_DUE_DATE, LAST_PROMISE_AMOUNT, EXCLUDE_DUNNING_FLAG, STAGED_DUNNING_LEVEL, DUNNING_LEVEL_OVERRIDE_DATE
, CONSOLIDATED_BILLING_NUMBER, LAST_COLLECTOR_CALLED, CURRENCY_DESCRIPTION, TRANSACTION_NUMBER, RECEIPT_NUMBER, CUSTOMER_NAME
, PAYMENT_TERM_NAME, OPERATING_UNIT, COLLECTOR_LAST, INVOICE_CURRENCY_CODE, CUSTOMER_TRX_ID, CASH_RECEIPT_ID, CUSTOMER_ID
, BILL_TO_SITE_USE_ID, SHIP_TO_SITE_USE_ID, TERM_ID, PAYMENT_TERM, ORG_ID, LAST_UPDATE_DATE, LAST_UPDATED_BY, CREATION_DATE, CREATED_BY) 
AS 
  SELECT /* UNIQUE ATTRIBUTES */ PS.PAYMENT_SCHEDULE_ID 
  , /* REGULAR ATTRIBUTES */ PS.DUE_DATE 
  , DECODE( PS.CLASS, 'BR', 'Bills Receivable', 'CB', 'Chargeback', 'CM', 'Credit Memo', 'DEP', 'Deposit', 'DM', 'Debit Memo', 'GUAR', 'Guarantee', 'INV', 'Invoice', 'PMT', 'Payment', NULL ) 
  , DECODE( PS.STATUS, 'CL', 'Closed', 'OP', 'Open', NULL ) 
  , PS.DISCOUNT_TAKEN_EARNED 
  , PS.DISCOUNT_TAKEN_UNEARNED 
  , PS.GL_DATE 
  , PS.AMOUNT_DUE_ORIGINAL 
  , PS.AMOUNT_DUE_REMAINING 
  , PS.AMOUNT_LINE_ITEMS_ORIGINAL 
  , PS.AMOUNT_LINE_ITEMS_REMAINING 
  , PS.FREIGHT_ORIGINAL 
  , PS.FREIGHT_REMAINING 
  , PS.TAX_ORIGINAL 
  , PS.TAX_REMAINING 
  , PS.AMOUNT_CREDITED 
  , PS.RECEIVABLES_CHARGES_CHARGED 
  , PS.RECEIVABLES_CHARGES_REMAINING 
--Functional Currency Amounts 
  , PS.ACCTD_AMOUNT_DUE_REMAINING 
  , PS.DISCOUNT_TAKEN_EARNED * NVL(PS.EXCHANGE_RATE,1)
  , PS.DISCOUNT_TAKEN_UNEARNED * NVL(PS.EXCHANGE_RATE,1)
  , PS.AMOUNT_DUE_ORIGINAL * NVL(PS.EXCHANGE_RATE,1)
  , PS.AMOUNT_LINE_ITEMS_ORIGINAL * NVL(PS.EXCHANGE_RATE,1)
  , PS.AMOUNT_LINE_ITEMS_REMAINING * NVL(PS.EXCHANGE_RATE,1)
  , PS.FREIGHT_ORIGINAL * NVL(PS.EXCHANGE_RATE,1)
  , PS.FREIGHT_REMAINING * NVL(PS.EXCHANGE_RATE,1)
  , PS.TAX_ORIGINAL * NVL(PS.EXCHANGE_RATE,1)
  , PS.TAX_REMAINING * NVL(PS.EXCHANGE_RATE,1)
  , PS.AMOUNT_CREDITED * NVL(PS.EXCHANGE_RATE,1)
  , PS.RECEIVABLES_CHARGES_CHARGED * NVL(PS.EXCHANGE_RATE,1)
  , PS.RECEIVABLES_CHARGES_REMAINING * NVL(PS.EXCHANGE_RATE,1)
----  
  , PS.EXCHANGE_RATE 
  , PS.EXCHANGE_RATE_TYPE 
  , PS.EXCHANGE_DATE 
  , PS.NUMBER_OF_DUE_DATES 
  , PS.TERMS_SEQUENCE_NUMBER 
  , PS.AMOUNT_IN_DISPUTE 
  , PS.DISPUTE_DATE 
  , PS.GL_DATE_CLOSED 
  , PS.ACTUAL_DATE_CLOSED 
  , DECODE( PS.IN_COLLECTION, 'N', 'No', 'Y', 'Yes', NULL ) 
  , PS.CALL_DATE_LAST 
  , DECODE( PS.FOLLOW_UP_CODE_LAST, 'CALL BACK', 'Call the customer again', 'VERIFY CHECK', 'Verify that a check has been received', 'VERIFY SHIPMENT', 'Verify that the shipment was sent', NULL ) 
  , PS.FOLLOW_UP_DATE_LAST 
  , PS.PROMISE_DATE_LAST 
  , PS.PROMISE_AMOUNT_LAST 
  , DECODE( PS.EXCLUDE_FROM_DUNNING_FLAG, 'N', 'No', 'Y', 'Yes', NULL ) 
  , PS.STAGED_DUNNING_LEVEL 
  , PS.DUNNING_LEVEL_OVERRIDE_DATE 
  , CI.CONS_BILLING_NUMBER 
  , COL.NAME 
  , CURR.DESCRIPTION 
  , CT.TRX_NUMBER 
  , CR.RECEIPT_NUMBER 
  , substrb(PARTY.PARTY_NAME,1,50)
  , TER.NAME 
  , AOU.NAME  
  , PS.COLLECTOR_LAST 
  , PS.INVOICE_CURRENCY_CODE 
  , PS.CUSTOMER_TRX_ID 
  , PS.CASH_RECEIPT_ID 
  , PS.CUSTOMER_ID 
  , CT.BILL_TO_SITE_USE_ID
  , CT.SHIP_TO_SITE_USE_ID
  , PS.TERM_ID 
  , TER.NAME
  , PS.ORG_ID 
  , PS.LAST_UPDATE_DATE 
  , PS.LAST_UPDATED_BY 
  , PS.CREATION_DATE 
  , PS.CREATED_BY 
  FROM AR_PAYMENT_SCHEDULES_all PS
  , AR_CONS_INV_all CI
  , AR_COLLECTORS COL
  , FND_CURRENCIES_VL CURR
  , RA_CUSTOMER_TRX_all CT
  , AR_CASH_RECEIPTS_all CR
  , HZ_PARTIES PARTY
  , HZ_CUST_ACCOUNTS CUST_ACCT
  , RA_TERMS TER, HR_ALL_ORGANIZATION_UNITS AOU 
  WHERE PS.CONS_INV_ID = CI.CONS_INV_ID (+) 
  AND PS.COLLECTOR_LAST = COL.COLLECTOR_ID (+) 
  AND PS.INVOICE_CURRENCY_CODE = CURR.CURRENCY_CODE 
  AND PS.CUSTOMER_TRX_ID = CT.CUSTOMER_TRX_ID (+) 
  AND PS.CASH_RECEIPT_ID = CR.CASH_RECEIPT_ID (+) 
  AND PS.CUSTOMER_ID = CUST_ACCT.CUST_ACCOUNT_ID (+) 
  AND PS.TERM_ID = TER.TERM_ID (+) 
  AND PS.ORG_ID = AOU.ORGANIZATION_ID (+) 
  AND CUST_ACCT.PARTY_ID = PARTY.PARTY_ID WITH READ ONLY
 ;
