/*
  Filename         :  XXAR_AR_INVOICE_HEADERS_V.SQL

  Purpose          :  Display information about AR Invoice Headers to be use for 
                   :  OBIEE reporting. 
                   :  CHG0034077
 
  Change History   :
  ............................................................
 --  ver  date               name                             desc
 --  1.0  15/02/2015    John Hendrickson           CHG0034077 initial build
  ............................................................
*/
  Create Or Replace View "XXBI"."XXAR_AR_INVOICE_HEADERS_V" ("TRANSACTION_ID", "TRANSACTION_NUMBER", "DOCUMENT_SEQUENCE_NUMBER", "TRANSACTION_DATE", "INVOICE_CURRENCY_CODE"
  , "CURRENCY_EXCHANGE_RATE", "CURRENCY_EXCHANGE_RATE_TYPE", "CURRENCY_EXCHANGE_RATE_DATE", "COMPLETE_FLAG", "TRANSACTION_STATUS", "PURCHASE_ORDER_NUMBER", "PURCHASE_ORDER_DATE"
  , "PURCHASE_ORDER_REVISION", "REASON_CODE", "REFERENCE_NUMBER", "FINANCE_CHARGES_FLAG", "DUE_DATE", "TAX_EXEMPT_FLAG", "FREIGHT_CARRIER", "SHIP_DATE", "SHIPPING_REFERENCE"
  , "FOB_POINT", "EDI_PROCESSED_FLAG", "FIRST_PRINT_DATE", "LAST_PRINT_DATE", "PENDING_PRINT_FLAG", "PRINTING_COUNT", "ORIGINAL_SYSTEM_BATCH_NAME", "BATCH_SOURCE_NAME", "TRANSACTION_TYPE_NAME"
  , "ATTRIBUTE_CATEGORY", "INTERFACE_HEADER_CONTEXT", "INTERFACE_HEADER_ATTRIBUTE1", "INTERFACE_HEADER_ATTRIBUTE2"  , "INTERFACE_HEADER_ATTRIBUTE3", "INTERFACE_HEADER_ATTRIBUTE4"
  , "INTERFACE_HEADER_ATTRIBUTE5", "INTERFACE_HEADER_ATTRIBUTE6", "INTERFACE_HEADER_ATTRIBUTE7", "INTERFACE_HEADER_ATTRIBUTE8"  , "INTERFACE_HEADER_ATTRIBUTE9", "INTERFACE_HEADER_ATTRIBUTE10"
  , "INTERFACE_HEADER_ATTRIBUTE11", "INTERFACE_HEADER_ATTRIBUTE12", "INTERFACE_HEADER_ATTRIBUTE13", "INTERFACE_HEADER_ATTRIBUTE14"  , "INTERFACE_HEADER_ATTRIBUTE15", "GLOBAL_ATTRIBUTE_CATEGORY"
  , "GLOBAL_ATTRIBUTE1", "GLOBAL_ATTRIBUTE2", "GLOBAL_ATTRIBUTE3", "GLOBAL_ATTRIBUTE4", "GLOBAL_ATTRIBUTE5", "GLOBAL_ATTRIBUTE6"  , "GLOBAL_ATTRIBUTE7", "GLOBAL_ATTRIBUTE8", "GLOBAL_ATTRIBUTE9"
  , "GLOBAL_ATTRIBUTE10", "GLOBAL_ATTRIBUTE11", "GLOBAL_ATTRIBUTE12", "GLOBAL_ATTRIBUTE13", "GLOBAL_ATTRIBUTE14", "GLOBAL_ATTRIBUTE15"
  , "BATCH_ID", "BATCH_SOURCE_ID", "CUST_TRX_TYPE_ID", "PRIMARY_SALESREP_ID", "BILL_TO_SITE_USE_ID", "SHIP_TO_SITE_USE_ID", "SOLD_TO_SITE_USE_ID", "PAYING_SITE_USE_ID", "RECEIPT_METHOD_ID", "ORG_ID"
  , "LAST_UPDATE_DATE", "LAST_UPDATED_BY", "CREATION_DATE", "CREATED_BY", "INTERNAL_NOTES", "COMMENTS") AS 
  SELECT
    /* UNIQUE ATTRIBUTES */
    CT.CUSTOMER_TRX_ID TRANSACTION_ID ,
    /* REGULAR ATTRIBUTES */
    CT.TRX_NUMBER TRANSACTION_NUMBER ,
    CT.DOC_SEQUENCE_VALUE DOCUMENT_SEQUENCE_NUMBER ,
    CT.TRX_DATE TRANSACTION_DATE ,
    CT.INVOICE_CURRENCY_CODE INVOICE_CURRENCY_CODE ,
    CT.EXCHANGE_RATE CURRENCY_EXCHANGE_RATE ,
    CT.EXCHANGE_RATE_TYPE CURRENCY_EXCHANGE_RATE_TYPE ,
    Ct.Exchange_Date Currency_Exchange_Rate_Date ,
    CT.COMPLETE_FLAG ,
    CT.STATUS_TRX ,
    CT.PURCHASE_ORDER PURCHASE_ORDER_NUMBER ,
    CT.PURCHASE_ORDER_DATE PURCHASE_ORDER_DATE ,
    CT.PURCHASE_ORDER_REVISION PURCHASE_ORDER_REVISION ,
    CT.REASON_CODE REASON_CODE ,
    CT.CT_REFERENCE REFERENCE_NUMBER ,
    CT.FINANCE_CHARGES ,
    CT.TERM_DUE_DATE DUE_DATE ,
    CT.DEFAULT_TAX_EXEMPT_FLAG ,
    CT.SHIP_VIA FREIGHT_CARRIER ,
    CT.SHIP_DATE_ACTUAL SHIP_DATE ,
    CT.WAYBILL_NUMBER SHIPPING_REFERENCE ,
    CT.FOB_POINT,
    CT.EDI_PROCESSED_FLAG,
    CT.PRINTING_ORIGINAL_DATE FIRST_PRINT_DATE ,
    CT.PRINTING_LAST_PRINTED LAST_PRINT_DATE ,
    CT.PRINTING_PENDING ,
    CT.PRINTING_COUNT PRINTING_COUNT ,
    Ct.Orig_System_Batch_Name Original_System_Batch_Name ,
    BATSRC.NAME BATCH_SOURCE_NAME ,
    Ctt.Name Transaction_Type_Name ,
    Ct.Attribute_Category,
    CT.INTERFACE_HEADER_CONTEXT,
    CT.INTERFACE_HEADER_ATTRIBUTE1,
    CT.INTERFACE_HEADER_ATTRIBUTE2,
    CT.INTERFACE_HEADER_ATTRIBUTE3,
    CT.INTERFACE_HEADER_ATTRIBUTE4,
    CT.INTERFACE_HEADER_ATTRIBUTE5,
    CT.INTERFACE_HEADER_ATTRIBUTE6,
    CT.INTERFACE_HEADER_ATTRIBUTE7,
    CT.INTERFACE_HEADER_ATTRIBUTE8,
    Ct.Interface_Header_Attribute9,
    Ct.Interface_Header_Attribute10,
    Ct.Interface_Header_Attribute11,
    Ct.Interface_Header_Attribute12,
    Ct.Interface_Header_Attribute13,
    Ct.Interface_Header_Attribute14,
    CT.INTERFACE_HEADER_ATTRIBUTE15,
    Ct.Global_Attribute_Category,
    CT.GLOBAL_ATTRIBUTE1,
    CT.GLOBAL_ATTRIBUTE2,
    CT.GLOBAL_ATTRIBUTE3,
    CT.GLOBAL_ATTRIBUTE4,
    CT.GLOBAL_ATTRIBUTE5,
    CT.GLOBAL_ATTRIBUTE6,
    CT.GLOBAL_ATTRIBUTE7,
    CT.GLOBAL_ATTRIBUTE8,
    CT.GLOBAL_ATTRIBUTE9,
    CT.GLOBAL_ATTRIBUTE10,
    Ct.Global_Attribute11,
    CT.GLOBAL_ATTRIBUTE12,
    Ct.Global_Attribute13,
    Ct.Global_Attribute14,
    CT.GLOBAL_ATTRIBUTE15,
    /* IDS */
    CT.BATCH_ID BATCH_ID ,
    CT.BATCH_SOURCE_ID BATCH_SOURCE_ID ,
    CT.CUST_TRX_TYPE_ID CUST_TRX_TYPE_ID ,
    CT.PRIMARY_SALESREP_ID PRIMARY_SALESREP_ID ,
    CT.BILL_TO_SITE_USE_ID BILL_TO_SITE_USE_ID ,
    CT.SHIP_TO_SITE_USE_ID SHIP_TO_SITE_USE_ID ,
    CT.SOLD_TO_SITE_USE_ID SOLD_TO_SITE_USE_ID ,
    CT.PAYING_SITE_USE_ID PAYING_SITE_USE_ID ,
    CT.RECEIPT_METHOD_ID RECEIPT_METHOD_ID ,
    CT.ORG_ID ORG_ID ,
    /* WHO COLUMNS */
    CT.LAST_UPDATE_DATE LAST_UPDATE_DATE ,
    CT.LAST_UPDATED_BY LAST_UPDATED_BY ,
    CT.CREATION_DATE CREATION_DATE ,
    CT.CREATED_BY CREATED_BY,
    CT.INTERNAL_NOTES INTERNAL_NOTES,
    CT.COMMENTS COMMENTS
  From  Apps.Ra_Customer_Trx_All Ct ,
        Apps.Ra_Batch_Sources_All Batsrc ,
        Apps.Ra_Cust_Trx_Types_All Ctt
  Where Ct.Batch_Source_Id                              = Batsrc.Batch_Source_Id
  AND CT.ORG_ID                                         = BATSRC.ORG_ID
  And Ct.Cust_Trx_Type_Id                               = Ctt.Cust_Trx_Type_Id
  AND CT.ORG_ID                                         = CTT.ORG_ID;