create or replace view xxcs_move_orders_v as
select mrh.header_id,
    mrh.request_number,
    mrh.transaction_type_id,
    mrh.transaction_type_name,
    mrh.move_order_type,
    mrh.move_order_type_name,
    mrh.organization_id,
    mrh.description,
    mrh.date_required,
    mrh.from_subinventory_code,
    mrh.to_subinventory_code,
    mrh.to_account_id,
    mrh.ship_to_location_id,
    mrh.header_status,
    mrh.header_status_name,
    mrh.status_date,
    mrh.creation_date,
    mrh.request_id,
    mrh.program_application_id,
    mrh.program_id,
    mrh.program_update_date,
    mrh.reference_id,
    mrh.reference_detail_id,
    mrh.attribute1 debrief_header_id,
    mrl.line_id,
    mrl.transaction_source_type_id,
    mrl.transaction_action_id,
    mrl.line_number,
    mrl.inventory_item_id,
    mrl.revision,
    mrl.from_subinventory_id,
    mrl.from_sub_locator_type,
    mrl.from_sub_asset,
    mrl.from_sub_quantity_tracked,
    mrl.from_sub_material_account,
    mrl.from_locator_id,
    mrl.to_sub_locator_type,
    mrl.to_sub_asset,
    mrl.to_sub_quantity_tracked,
    mrl.to_sub_material_account,
    mrl.to_subinventory_id,
    mrl.to_locator_id,
    mrl.lot_number,
    mrl.uom_code,
    mrl.quantity,
    mrl.required_quantity,
    mrl.quantity_delivered,
    mrl.quantity_detailed,
    mrl.reason_id,
    mrl.reference,
    mrl.reference_type_code,
    mrl.project_id,
    mrl.task_id,
    mrl.transaction_header_id,
    mrl.line_status,
    mrl.attribute1 debrief_line_id,
    mrl.attribute2 incident_id
from mtl_txn_request_headers_v mrh,
       mtl_txn_request_lines_v mrl
where mrh.header_id = mrl.header_id;

