create or replace view xxcs_debrief_v as
select cdh.debrief_header_id,
    to_char(cdh.debrief_header_id) debrief_header_id_chr,
    cdh.debrief_number,
    cdh.debrief_date,
    cdh.debrief_status_id,
    cdh.task_id,
    cdh.task_number,
    cdh.task_source,
    cdh.task_name,
    cdh.task_description,
    cdh.task_status,
    cdh.task_assignment_status,
    cdh.processed_flag,
    cdh.scheduled_start_date,
    cdh.creation_date,
    cdh.customer_number,
    cdh.customer_name,
    cdh.customer_id,
    cdh.cust_account_id,
    cdh.address,
    cdh.city_state_zip,
    cdh.resource_id,
    cdh.resource_name,
    cdh.resource_type,
    cdh.source_number,
    cdh.incident_id,
    cdh.product_id,
    cdh.product_name,
    cdh.product_description,
    cdh.organization_id,
    cdp.debrief_line_id,
    to_char(debrief_line_id) debrief_line_id_chr,
    cdp.channel_code,
    cdp.service_date,
    cdp.inventory_item_id,
    msi.segment1 item_number,
    msi.description,
    cdp.uom_code,
    cdp.labor_start_date,
    cdp.labor_end_date,
    cdp.quantity,
    cdp.business_process_id,
    cdp.transaction_type_id,
    cdp.txn_type,
    cdp.txn_type_description,
    cdp.charge_upload_status,
    cdp.expense_amount,
    cdp.currency_code,
    cdp.expense_meaning,
    cdp.instance_id,
    cdp.instance_number,
    cdp.inventory_org_id,
    cdp.sub_inventory_code,
    cdp.parent_product_id,
    cdp.removed_product_id,
    cdp.item_revision,
    cdp.item_serial_number,
    cdp.line_order_category_code,
    cdp.material_meaning,
    cdp.ib_update_status,
    cdp.spare_update_status,
    cdp.return_reason_code,
    cdp.return_reason,
    cdp.error_text,
    cdp.attribute1,
    cdp.attribute2,
    cdp.attribute3,
    cdp.attribute4,
    cdp.attribute5,
    cdp.attribute6,
    cdp.attribute7,
    cdp.attribute8,
    cdp.attribute9,
    cdp.attribute10,
    cdp.attribute11,
    cdp.attribute12,
    cdp.attribute13,
    cdp.attribute14,
    cdp.attribute15,
    cdp.line_type
from csf_debrief_headers_v cdh,
       xxcs_debrief_pertasks_v cdp,
       mtl_system_items_b msi
where cdh.debrief_header_id = cdp.debrief_header_id
 and msi.organization_id = cdh.organization_id
 and msi.inventory_item_id = cdp.inventory_item_id (+)
 and cdh.organization_id = 91;

