CREATE OR REPLACE VIEW XXCS_MATERIAL_TRANSACTIONS_V AS
SELECT
--------------------------------------------------------------------
--  name:            XXCS_MATERIAL_TRANSACTIONS_V
--  create by:       Roman
--  Revision:        1.1
--  creation date:   25/07/2010
--------------------------------------------------------------------
--  purpose :        Disco Report:  XX: CS Material Transactions
--------------------------------------------------------------------
--  ver  date        name             desc
--  1.0  25/07/2009  Roman           initial build
--  1.1  26/07/2009  Roman           Added owner and org parameters
--------------------------------------------------------------------
 TRX.TRANSACTION_ID,
 RES.RESOURCE_NAME   OWNER,
 TRX.SUBINVENTORY_CODE,
 TRX.TRANSACTION_DATE,
 TRX.SEGMENT1,
 TRX.DESCRIPTION,
 TRX.TRANSACTION_QUANTITY,
 TRX.SOURCE_CODE REFERENCE,
 TRX.REFERENCE_NUMBER,
 TRX.TRANSACTION_TYPE_NAME,
 TRX.ORGANIZATION_ID,
 FU.USER_NAME PERFORMED_BY,
 OOD.ORGANIZATION_CODE INV_ORG,
 OU.NAME OPRATING_UNIT
  FROM (SELECT MMT.TRANSACTION_ID,
               MMT.SUBINVENTORY_CODE,
               MMT.TRANSACTION_DATE,
               MSIB.SEGMENT1,
               MSIB.DESCRIPTION,
               MMT.TRANSACTION_QUANTITY,
               DECODE(MMT.SOURCE_CODE, 'CSP', 'Debrief') SOURCE_CODE,
               JTB.SOURCE_OBJECT_NAME REFERENCE_NUMBER,
               MTT.TRANSACTION_TYPE_NAME,
               MMT.CREATED_BY,
               MMT.ORGANIZATION_ID
          FROM MTL_MATERIAL_TRANSACTIONS MMT,
               MTL_SYSTEM_ITEMS_B        MSIB,
               MTL_SECONDARY_INVENTORIES MSI,
               CSF_DEBRIEF_HEADERS       CDH,
               JTF_TASK_ASSIGNMENTS      JTA,
               JTF_TASKS_B               JTB,
               MTL_TRANSACTION_TYPES     MTT
         WHERE MMT.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
           AND MSI.SECONDARY_INVENTORY_NAME = MMT.SUBINVENTORY_CODE
           AND MSIB.ORGANIZATION_ID = 91
           AND CDH.DEBRIEF_NUMBER = MMT.TRANSACTION_SOURCE_NAME
           AND CDH.TASK_ASSIGNMENT_ID = JTA.TASK_ASSIGNMENT_ID
           AND JTA.TASK_ID = JTB.TASK_ID
           AND MMT.TRANSACTION_TYPE_ID = 93
           AND MTT.TRANSACTION_TYPE_ID = MMT.TRANSACTION_TYPE_ID
        UNION ALL
        SELECT MMT.TRANSACTION_ID,
               MMT.SUBINVENTORY_CODE,
               MMT.TRANSACTION_DATE,
               MSIB.SEGMENT1,
               MSIB.DESCRIPTION,
               MMT.TRANSACTION_QUANTITY,
               DECODE(MMT.SOURCE_CODE, 'CSP', 'Debrief') REFERENCE,
               JTB.SOURCE_OBJECT_NAME REFERENCE_NUMBER,
               MTT.TRANSACTION_TYPE_NAME,
               MMT.CREATED_BY,
               MMT.ORGANIZATION_ID
          FROM MTL_MATERIAL_TRANSACTIONS MMT,
               MTL_SYSTEM_ITEMS_B        MSIB,
               MTL_SECONDARY_INVENTORIES MSI,
               CSF_DEBRIEF_HEADERS       CDH,
               JTF_TASK_ASSIGNMENTS      JTA,
               JTF_TASKS_B               JTB,
               MTL_TRANSACTION_TYPES     MTT
         WHERE MMT.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
           AND MSI.SECONDARY_INVENTORY_NAME = MMT.SUBINVENTORY_CODE
           AND MSIB.ORGANIZATION_ID = 91
           AND CDH.DEBRIEF_NUMBER = MMT.TRANSACTION_SOURCE_NAME
           AND CDH.TASK_ASSIGNMENT_ID = JTA.TASK_ASSIGNMENT_ID
           AND JTA.TASK_ID = JTB.TASK_ID
           AND MMT.TRANSACTION_TYPE_ID = 94
           AND MTT.TRANSACTION_TYPE_ID = MMT.TRANSACTION_TYPE_ID
        UNION ALL
        SELECT MMT.TRANSACTION_ID,
               MMT.SUBINVENTORY_CODE,
               MMT.TRANSACTION_DATE,
               MSIB.SEGMENT1,
               MSIB.DESCRIPTION,
               MMT.TRANSACTION_QUANTITY,
               DECODE(MMT.SOURCE_CODE,
                      'ORDER ENTRY',
                      'Service Internal Order') REFERENCE,
               JTB.SOURCE_OBJECT_NAME REFERENCE_NUMBER,
               MTT.TRANSACTION_TYPE_NAME,
               MMT.CREATED_BY,
               MMT.ORGANIZATION_ID
          FROM MTL_MATERIAL_TRANSACTIONS MMT,
               MTL_SYSTEM_ITEMS_B        MSIB,
               MTL_SECONDARY_INVENTORIES MSI,
               OE_ORDER_HEADERS_ALL      OOHA,
               OE_ORDER_LINES_ALL        OOLA,
               CSP_REQ_LINE_DETAILS_V    CRL,
               CSP_REQUIREMENT_HEADERS   CRH,
               JTF_TASKS_B               JTB,
               MTL_TRANSACTION_TYPES     MTT
         WHERE MMT.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
           AND MSI.SECONDARY_INVENTORY_NAME = MMT.SUBINVENTORY_CODE
           AND MSIB.ORGANIZATION_ID = 91
           AND MMT.SOURCE_LINE_ID = OOLA.LINE_ID
           AND OOLA.HEADER_ID = OOHA.HEADER_ID
           AND CRL.source_id = OOLA.LINE_ID
           AND CRL.REQUIREMENT_HEADER_ID = CRH.REQUIREMENT_HEADER_ID
           AND CRH.TASK_ID = JTB.TASK_ID
           AND MMT.TRANSACTION_TYPE_ID = 96
           AND MTT.TRANSACTION_TYPE_ID = MMT.TRANSACTION_TYPE_ID
        UNION ALL
        SELECT MMT.TRANSACTION_ID,
               MMT.SUBINVENTORY_CODE,
               MMT.TRANSACTION_DATE,
               MSIB.SEGMENT1,
               MSIB.DESCRIPTION,
               MMT.TRANSACTION_QUANTITY,
               'Internal order' REFERENCE,
               TO_CHAR(OOHA.ORDER_NUMBER) REFERENCE_NUMBER,
               MTT.TRANSACTION_TYPE_NAME,
               MMT.CREATED_BY,
               MMT.ORGANIZATION_ID
          FROM MTL_MATERIAL_TRANSACTIONS MMT,
               MTL_SYSTEM_ITEMS_B        MSIB,
               MTL_SECONDARY_INVENTORIES MSI,
               OE_ORDER_HEADERS_ALL      OOHA,
               OE_ORDER_LINES_ALL        OOLA,
               MTL_TRANSACTION_TYPES     MTT
         WHERE MMT.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
           AND MSI.SECONDARY_INVENTORY_NAME = MMT.SUBINVENTORY_CODE
           AND MSIB.ORGANIZATION_ID = 91
           AND MMT.TRX_SOURCE_LINE_ID = OOLA.LINE_ID
           AND OOLA.HEADER_ID = OOHA.HEADER_ID
           AND MMT.TRANSACTION_TYPE_ID = 53
           AND MTT.TRANSACTION_TYPE_ID = MMT.TRANSACTION_TYPE_ID
        UNION ALL
        SELECT MMT.TRANSACTION_ID,
               MMT.SUBINVENTORY_CODE,
               MMT.TRANSACTION_DATE,
               MSIB.SEGMENT1,
               MSIB.DESCRIPTION,
               MMT.TRANSACTION_QUANTITY,
               'Subinventory Transfer' REFERENCE,
               '' REFERENCE_NUMBER,
               MTT.TRANSACTION_TYPE_NAME,
               MMT.CREATED_BY,
               MMT.ORGANIZATION_ID
          FROM MTL_MATERIAL_TRANSACTIONS MMT,
               MTL_SYSTEM_ITEMS_B        MSIB,
               MTL_SECONDARY_INVENTORIES MSI,
               MTL_TRANSACTION_TYPES     MTT
         WHERE MMT.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
           AND MSI.SECONDARY_INVENTORY_NAME = MMT.SUBINVENTORY_CODE
           AND MSIB.ORGANIZATION_ID = 91
           AND MMT.TRANSACTION_TYPE_ID = 2
           AND MTT.TRANSACTION_TYPE_ID = MMT.TRANSACTION_TYPE_ID
        UNION ALL
        SELECT MMT.TRANSACTION_ID,
               MMT.SUBINVENTORY_CODE,
               MMT.TRANSACTION_DATE,
               MSIB.SEGMENT1,
               MSIB.DESCRIPTION,
               MMT.TRANSACTION_QUANTITY,
               'Physical Inv Adjust' REFERENCE,
               MMT.TRANSACTION_REFERENCE REFERENCE_NUMBER,
               MTT.TRANSACTION_TYPE_NAME,
               MMT.CREATED_BY,
               MMT.ORGANIZATION_ID
          FROM MTL_MATERIAL_TRANSACTIONS MMT,
               MTL_SYSTEM_ITEMS_B        MSIB,
               MTL_SECONDARY_INVENTORIES MSI,
               MTL_TRANSACTION_TYPES     MTT
         WHERE MMT.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
           AND MSI.SECONDARY_INVENTORY_NAME = MMT.SUBINVENTORY_CODE
           AND MSIB.ORGANIZATION_ID = 91
           AND MMT.TRANSACTION_TYPE_ID = 8
           AND MTT.TRANSACTION_TYPE_ID = MMT.TRANSACTION_TYPE_ID
        UNION ALL
        SELECT MMT.TRANSACTION_ID,
               MMT.SUBINVENTORY_CODE,
               MMT.TRANSACTION_DATE,
               MSIB.SEGMENT1,
               MSIB.DESCRIPTION,
               MMT.TRANSACTION_QUANTITY,
               'Move order' REFERENCE,
               H.DESCRIPTION REFERENCE_NUMBER,
               MTT.TRANSACTION_TYPE_NAME,
               MMT.CREATED_BY,
               MMT.ORGANIZATION_ID
          FROM MTL_MATERIAL_TRANSACTIONS MMT,
               MTL_SYSTEM_ITEMS_B        MSIB,
               MTL_SECONDARY_INVENTORIES MSI,
               MTL_TRANSACTION_TYPES     MTT,
               MTL_TXN_REQUEST_HEADERS   H,
               CS_INCIDENTS_ALL_B        CIAB
         WHERE MMT.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
           AND MSI.SECONDARY_INVENTORY_NAME = MMT.SUBINVENTORY_CODE
           AND MSIB.ORGANIZATION_ID = 91
           AND MMT.TRANSACTION_TYPE_ID = 64
           AND MTT.TRANSACTION_TYPE_ID = MMT.TRANSACTION_TYPE_ID
           AND MMT.TRANSACTION_SOURCE_ID = H.HEADER_ID
           AND H.DESCRIPTION = CIAB.INCIDENT_NUMBER(+)
        UNION ALL
        SELECT MMT.TRANSACTION_ID,
               MMT.SUBINVENTORY_CODE,
               MMT.TRANSACTION_DATE,
               MSIB.SEGMENT1,
               MSIB.DESCRIPTION,
               MMT.TRANSACTION_QUANTITY,
               SOURCE_CODE REFERENCE,
               MMT.TRANSACTION_REFERENCE REFERENCE_NUMBER,
               MTT.TRANSACTION_TYPE_NAME,
               MMT.CREATED_BY,
               MMT.ORGANIZATION_ID
          FROM MTL_MATERIAL_TRANSACTIONS MMT,
               MTL_SYSTEM_ITEMS_B        MSIB,
               MTL_SECONDARY_INVENTORIES MSI,
               MTL_TRANSACTION_TYPES     MTT
         WHERE MMT.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
           AND MSI.SECONDARY_INVENTORY_NAME = MMT.SUBINVENTORY_CODE
           AND MSIB.ORGANIZATION_ID = 91
           AND MMT.TRANSACTION_TYPE_ID IN (41, 31)
           AND MTT.TRANSACTION_TYPE_ID = MMT.TRANSACTION_TYPE_ID) TRX,
       FND_USER FU,
       ORG_ORGANIZATION_DEFINITIONS OOD,
       HR_OPERATING_UNITS OU,
       CSP_SEC_INVENTORIES            CSI,
       XXCS_RESOURCES                 RES
 WHERE TRX.CREATED_BY = FU.USER_ID
   AND OOD.ORGANIZATION_ID = TRX.ORGANIZATION_ID
   AND OOD.OPERATING_UNIT = OU.ORGANIZATION_ID
   AND TRX.SUBINVENTORY_CODE = CSI.SECONDARY_INVENTORY_NAME
   AND CSI.OWNER_RESOURCE_ID = RES.RESOURCE_ID (+)
   AND XXCS_UTILS_PKG.CHECK_SECURITY_BY_OPER_UNIT(OOD.OPERATING_UNIT) = 'Y'
   /*AND TRX.TRANSACTION_DATE > '01-SEP-2009'
   AND TRX.TRANSACTION_DATE < '31-DEC-2010'
   AND TRX.SUBINVENTORY_CODE = 'S310 - NEW'*/
 ORDER BY 3 DESC;

